"""
app.py — Telco Customer Churn Prediction Prototype (Section 6 of the report)

Run with:  streamlit run app.py

Requires model.pkl, scaler.pkl, feature_columns.pkl in the same folder
(generated by running `python train_model.py` once beforehand).
"""

import pickle
import numpy as np
import pandas as pd
import streamlit as st

from codebase.eda import (
    engineer_and_clean,
    build_feature_matrix,
    NUM_COLS_TO_SCALE,
)

st.set_page_config(page_title="Telco Churn Predictor", page_icon="📡", layout="centered")


@st.cache_resource
def load_artifacts():
    with open("model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("scaler.pkl", "rb") as f:
        scaler = pickle.load(f)
    with open("feature_columns.pkl", "rb") as f:
        feature_columns = pickle.load(f)
    return model, scaler, feature_columns


model, scaler, feature_columns = load_artifacts()

st.title("📡 Telco Customer Churn Predictor")
st.caption(
    "Prototype deployment for the BMDS2003 Telco Customer Churn project. "
    "Enter a customer's profile to get a churn probability and risk category."
)

st.divider()

# ----------------------------------------------------------------------
# 6.2 Application Features — input form
# ----------------------------------------------------------------------
with st.form("customer_form"):
    st.subheader("Customer Profile")

    col1, col2 = st.columns(2)
    with col1:
        gender = st.selectbox("Gender", ["Female", "Male"])
        senior_citizen = st.selectbox("Senior Citizen", ["No", "Yes"])
        partner = st.selectbox("Has Partner", ["No", "Yes"])
        dependents = st.selectbox("Has Dependents", ["No", "Yes"])
        tenure = st.slider("Tenure (months)", 0, 72, 12)
        contract = st.selectbox("Contract Type", ["Month-to-month", "One year", "Two year"])
        paperless_billing = st.selectbox("Paperless Billing", ["No", "Yes"])
        payment_method = st.selectbox(
            "Payment Method",
            ["Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"],
        )

    with col2:
        monthly_charges = st.slider("Monthly Charges (USD)", 18.0, 120.0, 70.0, step=0.5)
        total_charges = st.number_input(
            "Total Charges (USD, leave as tenure x monthly if unsure)",
            min_value=0.0, value=float(round(tenure * monthly_charges, 2)),
        )
        phone_service = st.selectbox("Phone Service", ["No", "Yes"])
        multiple_lines = st.selectbox("Multiple Lines", ["No", "Yes"], disabled=(phone_service == "No"))
        internet_service = st.selectbox("Internet Service", ["DSL", "Fiber optic", "No"])

    st.markdown("**Internet Add-on Services** (only applicable if Internet Service is not 'No')")
    disable_internet_opts = internet_service == "No"
    c3, c4, c5 = st.columns(3)
    with c3:
        online_security = st.selectbox("Online Security", ["No", "Yes"], disabled=disable_internet_opts)
        online_backup = st.selectbox("Online Backup", ["No", "Yes"], disabled=disable_internet_opts)
    with c4:
        device_protection = st.selectbox("Device Protection", ["No", "Yes"], disabled=disable_internet_opts)
        tech_support = st.selectbox("Tech Support", ["No", "Yes"], disabled=disable_internet_opts)
    with c5:
        streaming_tv = st.selectbox("Streaming TV", ["No", "Yes"], disabled=disable_internet_opts)
        streaming_movies = st.selectbox("Streaming Movies", ["No", "Yes"], disabled=disable_internet_opts)

    submitted = st.form_submit_button("Predict Churn Risk", use_container_width=True)

# ----------------------------------------------------------------------
# Prediction
# ----------------------------------------------------------------------
if submitted:
    if internet_service == "No":
        online_security = online_backup = device_protection = "No"
        tech_support = streaming_tv = streaming_movies = "No"
    if phone_service == "No":
        multiple_lines = "No"

    raw_input = pd.DataFrame([{
        "customerID": "PROTOTYPE-INPUT",
        "gender": gender,
        "SeniorCitizen": 1 if senior_citizen == "Yes" else 0,
        "Partner": partner,
        "Dependents": dependents,
        "tenure": tenure,
        "PhoneService": phone_service,
        "MultipleLines": multiple_lines,
        "InternetService": internet_service,
        "OnlineSecurity": online_security,
        "OnlineBackup": online_backup,
        "DeviceProtection": device_protection,
        "TechSupport": tech_support,
        "StreamingTV": streaming_tv,
        "StreamingMovies": streaming_movies,
        "Contract": contract,
        "PaperlessBilling": paperless_billing,
        "PaymentMethod": payment_method,
        "MonthlyCharges": monthly_charges,
        "TotalCharges": total_charges,
        "Churn": "No",  # placeholder, dropped before prediction
    }])

    cleaned = engineer_and_clean(raw_input)
    X_input = build_feature_matrix(cleaned)

    # Align columns exactly to what the model was trained on
    X_input = X_input.reindex(columns=feature_columns, fill_value=0)

    # Scale the same numeric columns using the saved (train-fitted) scaler
    X_input_scaled = X_input.copy()
    X_input_scaled[NUM_COLS_TO_SCALE] = scaler.transform(X_input[NUM_COLS_TO_SCALE])

    proba = model.predict_proba(X_input_scaled)[0, 1]

    if proba < 0.40:
        risk_label, risk_color = "Low Risk", "green"
    elif proba < 0.70:
        risk_label, risk_color = "Medium Risk", "orange"
    else:
        risk_label, risk_color = "High Risk", "red"

    st.divider()
    st.subheader("Prediction Result")

    r1, r2 = st.columns(2)
    with r1:
        st.metric("Churn Probability", f"{proba*100:.1f}%")
    with r2:
        st.markdown(f"### :{risk_color}[{risk_label}]")

    st.progress(min(max(proba, 0.0), 1.0))

    # ------------------------------------------------------------------
    # Top contributing features for this prediction (model-level importance,
    # cross-referenced against this customer's actual values, per Section 6.2)
    # ------------------------------------------------------------------
    st.subheader("Top Factors Influencing This Prediction")
    importances = pd.Series(model.feature_importances_, index=feature_columns)
    top_features = importances.sort_values(ascending=False).head(6)

    display_rows = []
    for feat in top_features.index:
        val = X_input.iloc[0][feat]
        display_rows.append({"Feature": feat, "Model Importance": round(top_features[feat], 3),
                              "This Customer's Value": round(val, 2) if isinstance(val, (int, float, np.integer, np.floating)) else val})
    st.dataframe(pd.DataFrame(display_rows), hide_index=True, use_container_width=True)

    st.caption(
        "Importance is the Random Forest's overall feature importance (Section 5.3 of the report), "
        "shown alongside this customer's actual value for each top feature. This is a global "
        "importance ranking, not a per-prediction SHAP explanation — a natural extension for future work."
    )

    with st.expander("Show raw model input (debug)"):
        st.dataframe(X_input.T, use_container_width=True)

st.divider()
st.caption(
    "Model: Random Forest (n_estimators=200, max_depth=12, min_samples_leaf=5), "
    "trained on 23 predictors after a four-round multicollinearity audit (Section 3.3 of the report). "
    "Test-set performance: Accuracy 75.9%, Precision 53.3%, Recall 73.0%, F1 61.6%, AUC 0.839."
)