"""
app.py — Telco Customer Churn Prediction Prototype (Section 6 of the report)

Run with:  streamlit run app.py   (from this folder)
       or:  streamlit run streamlit/app.py   (from the project root)

Requires models.pkl, scaler.pkl, feature_columns.pkl in this folder
(generated by running `python train_model.py` once beforehand).

Three tabs:
  * Predict        — enter a customer profile, get a churn probability + risk tier
  * Data Analysis   — every EDA / data-preparation analysis from report Sections 2-3,
                       computed live from the raw dataset via the src/ analysis package
  * Models          — the full modelling / evaluation suite from report Sections 4-5,
                       computed live against the deployed models
"""

import os
import sys
import pickle
import time

import matplotlib
matplotlib.use("Agg")
import numpy as np
import pandas as pd
import streamlit as st

_HERE = os.path.dirname(os.path.abspath(__file__))
_SRC = os.path.abspath(os.path.join(_HERE, "..", "src"))
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from train_model import (  # noqa: E402  (local prototype module, mirrors src/data_prep.py)
    engineer_and_clean,
    build_feature_matrix as build_feature_matrix_proto,
    NUM_COLS_TO_SCALE,
    RAW_CSV_PATH,
)
import data_prep as dp  # noqa: E402
import eda  # noqa: E402
import eda_plots as epl  # noqa: E402
import modelling as md  # noqa: E402
import evaluation as ev  # noqa: E402
import plotly_charts as pc  # Plotly (interactive) chart layer — app-only, see file docstring
import model_interactions as miv  # Complex threshold/Sankey/3D visuals — display only
import prediction_visuals as pv  # Single-customer Predict result visuals
from sklearn.linear_model import LogisticRegression  # noqa: E402
from sklearn.tree import DecisionTreeClassifier  # noqa: E402
from sklearn.ensemble import RandomForestClassifier  # noqa: E402
from xgboost import XGBClassifier  # noqa: E402

# Visual design system (colours, icon maps, CSS, HTML/markdown helpers) lives
# in ui_style.py — keeps this file focused on data wiring + page flow.
from ui_style import (  # noqa: E402
    NAVY, BLUE, LIGHT, RED, GREEN, AMBER,
    MODEL_ICON, TIER_INFO,
    inject_css, sec, show_fig, mi, attach_predict_button_loader,
)
from tower_3d import render_tower_3d  # noqa: E402

_predict_loader_reset = st.components.v2.component(
    "predict_loader_reset_app_v1",
    html='<span aria-hidden="true"></span>',
    js=r"""
export default function(component) {
  component.parentElement.style.display='none';
  const button=component.parentElement.ownerDocument.querySelector(
    'div.st-key-predict_button button'
  );
  button?.classList.remove('predict-is-loading');
  button?.removeAttribute('aria-busy');
}
""",
    isolate_styles=False,
)


def finish_predict_button_loader():
    """Restore Predict after the fragment has finished rendering its result."""
    completion_token = time.time_ns()
    _predict_loader_reset(
        key=f"predict_loader_reset_{completion_token}",
        height=1,
    )

DEFAULT_MODEL = "Random Forest"  # recommended model, report Section 5.9

# Hold-out test metrics (report Section 5.2) — cross-checked against models.pkl
# on the true test split; kept as a display cache so the Predict-tab sidebar
# doesn't have to rerun evaluation on every widget interaction.
TEST_METRICS = {
    "Logistic Regression": dict(Accuracy=75.23, Precision=52.44, Recall=71.93, F1=60.65, AUC=0.833),
    "Decision Tree":       dict(Accuracy=73.74, Precision=50.35, Recall=77.01, F1=60.89, AUC=0.823),
    "Random Forest":       dict(Accuracy=75.87, Precision=53.31, Recall=73.26, F1=61.71, AUC=0.839),
    "XGBoost":             dict(Accuracy=75.23, Precision=52.40, Recall=72.99, F1=61.01, AUC=0.830),
}
MODEL_ROLE = {
    "Logistic Regression": "Linear baseline, interpretable.",
    "Decision Tree": "Readable tree, highest recall.",
    "Random Forest": "Best overall — recommended.",
    "XGBoost": "Gradient-boosted, strong.",
}

ADDON_SERVICES = ["OnlineSecurity", "OnlineBackup", "DeviceProtection",
                  "TechSupport", "StreamingTV", "StreamingMovies"]
ADDON_LABELS = {"OnlineSecurity": "Online Security", "OnlineBackup": "Online Backup",
                "DeviceProtection": "Device Protection", "TechSupport": "Tech Support",
                "StreamingTV": "Streaming TV", "StreamingMovies": "Streaming Movies"}
CONTRACT_RISK = {"Month-to-month": 2, "One year": 1, "Two year": 0}

# Demo presets — grounded in the report's findings (Sections 2.5 / 2.7)
PRESETS = {
    "Highest-risk segment": dict(
        gender="Female", senior="No", partner="No", dependents="No", tenure=2,
        contract="Month-to-month", paperless="Yes", payment="Electronic check",
        monthly=95.0, phone="Yes", lines="No", internet="Fiber optic",
        addons={c: "No" for c in ADDON_SERVICES}),
    "Lowest-risk segment": dict(
        gender="Male", senior="No", partner="Yes", dependents="Yes", tenure=68,
        contract="Two year", paperless="No", payment="Credit card (automatic)",
        monthly=62.0, phone="Yes", lines="Yes", internet="DSL",
        addons={c: "Yes" for c in ADDON_SERVICES}),
    "Dataset average": dict(
        gender="Female", senior="No", partner="No", dependents="No", tenure=32,
        contract="Month-to-month", paperless="Yes", payment="Electronic check",
        monthly=64.5, phone="Yes", lines="No", internet="Fiber optic",
        addons={c: "No" for c in ADDON_SERVICES}),
}

st.set_page_config(page_title="Telco Churn Predictor", page_icon="📡", layout="wide",
                   initial_sidebar_state="expanded")

# ----------------------------------------------------------------------
# Styling — full CSS + visual helpers live in ui_style.py
# ----------------------------------------------------------------------
inject_css()

st.markdown(
    '<div class="app-banner"><div class="t">Telco Customer Churn Predictor</div>'
    '<div class="s">Predict churn risk, explore the analysis behind the model, '
    'and compare all four models side by side</div></div>',
    unsafe_allow_html=True,
)


# ----------------------------------------------------------------------
# Cached loaders
# ----------------------------------------------------------------------
@st.cache_resource
def load_artifacts():
    """
    Loads the three trained-model artifacts this app depends on. This is the app's
    single external-file dependency (everything else is computed live from data/ via
    src/), so it's the one place worth a friendly failure message instead of a raw
    traceback — most likely to break during a live demo on a machine that hasn't run
    `python train_model.py` yet, or after a fresh git clone.
    """
    try:
        with open(os.path.join(_HERE, "models.pkl"), "rb") as f:
            models = pickle.load(f)
        with open(os.path.join(_HERE, "scaler.pkl"), "rb") as f:
            scaler = pickle.load(f)
        with open(os.path.join(_HERE, "feature_columns.pkl"), "rb") as f:
            feature_columns = pickle.load(f)
    except FileNotFoundError as e:
        st.error(
            "**Model artifacts not found.** This app needs `models.pkl`, `scaler.pkl`, "
            "and `feature_columns.pkl` in the `streamlit/` folder before it can run.\n\n"
            f"Missing file: `{os.path.basename(e.filename)}`\n\n"
            "Fix: open a terminal in the `streamlit/` folder and run:\n"
            "```\npython train_model.py\n```\n"
            "then reload this page."
        )
        st.stop()
    except Exception as e:
        st.error(
            f"**Could not load model artifacts** ({type(e).__name__}: {e}).\n\n"
            "This usually means the `.pkl` files were trained with a different library "
            "version than what's installed here. Fix: run `pip install -r requirement.txt` "
            "then `python train_model.py` again in the `streamlit/` folder, and reload this page."
        )
        st.stop()
    return models, scaler, feature_columns


@st.cache_data(show_spinner="Loading and preparing dataset...")
def load_eda_data():
    """Full EDA dataframe (all engineered features, for reporting) + the final
    23-predictor modelling matrix — the same src/data_prep.py pipeline the
    notebook and report use."""
    df_eda, X, y = dp.full_pipeline()
    return df_eda, X, y


@st.cache_data
def contract_tenure_reference():
    """
    How real customers distribute across Contract within each tenure band, plus the
    observed churn rate per (tenure band, contract) cell. Used by the Predict tab to
    tell the user how plausible their combination is — Contract is the customer's
    *current* contract, not a lifetime commitment, so every combination is legal,
    but they are far from equally common (Section 2.5).
    """
    df, _, _ = load_eda_data()
    d = df.copy()
    d["_tg"] = pd.cut(d["tenure"], [-1, 12, 24, 48, 60, 200],
                      labels=["0-12", "13-24", "25-48", "49-60", "61+"])
    d["_c"] = (d["Churn"] == "Yes").astype(int)
    share = pd.crosstab(d["_tg"], d["Contract"], normalize="index") * 100
    churn = d.pivot_table("_c", "_tg", "Contract", observed=True) * 100
    counts = pd.crosstab(d["_tg"], d["Contract"])
    return share.round(1), churn.round(1), counts


@st.cache_resource(show_spinner="Reconstructing the train/test split and SMOTE resample...")
def build_eval_bundle(feature_columns):
    """
    Rebuilds the exact 80/20 stratified split, StandardScaler fit, and SMOTE
    resample used throughout the report (Sections 3.6-3.8), then aligns columns
    to the deployed models so the app can evaluate the *actual shipped* models
    (models.pkl) rather than retraining fresh ones.
    """
    df_eda, X, y = load_eda_data()
    X_train, X_test, y_train, y_test = md.split_data(X, y)
    X_train_scaled, X_test_scaled, _ = md.scale_features(X_train, X_test)
    X_train_sm, y_train_sm = md.resample_smote(X_train_scaled, y_train)
    X_test_scaled = X_test_scaled.reindex(columns=list(feature_columns), fill_value=0)
    X_train_sm = X_train_sm.reindex(columns=list(feature_columns), fill_value=0)
    return X_train_sm, y_train_sm, X_test_scaled, y_test


@st.cache_data(show_spinner="Running 5-fold stratified cross-validation (all four models)...")
def compute_cv_results():
    """Report Section 4.3 — fresh SMOTE per fold via an imblearn Pipeline, using the
    exact deployed hyperparameters (not re-run through GridSearchCV, for app speed)."""
    df_eda, X, y = load_eda_data()
    X_train, X_test, y_train, y_test = md.split_data(X, y)
    X_train_scaled, _, _ = md.scale_features(X_train, X_test)
    builders = {
        "Logistic Regression": LogisticRegression(max_iter=2000, random_state=42),
        "Decision Tree": DecisionTreeClassifier(max_depth=5, min_samples_split=10, random_state=42),
        "Random Forest": RandomForestClassifier(n_estimators=200, max_depth=12, min_samples_leaf=5, random_state=42),
        "XGBoost": XGBClassifier(max_depth=4, learning_rate=0.1, n_estimators=150, min_child_weight=10,
                                  subsample=0.8, colsample_bytree=0.8, reg_lambda=1,
                                  random_state=42, eval_metric="logloss"),
    }
    return ev.kfold_cv_all_models(X_train_scaled, y_train, builders)


@st.cache_data(show_spinner="Computing Variance Inflation Factors...")
def compute_vif_table(feature_columns):
    df_eda, X, y = load_eda_data()
    X = X.reindex(columns=list(feature_columns), fill_value=0)
    return eda.compute_vif(X.astype(float))


models, scaler, feature_columns = load_artifacts()

# ----------------------------------------------------------------------
# Top control strip — one model selector shared by Predict and every
# model-specific interactive view. Comparison views may still show all four
# models, but the selected model remains the application-wide focus.
# ----------------------------------------------------------------------
top1, top2, top3 = st.columns([1.1, 1.6, 1.1])
with top1:
    st.markdown("**Model**")
    # 4 stacked click-cards instead of a dropdown — Test-set performance (2 rows)
    # and Demo presets (3 rows) both run taller than a single-line select ever
    # would, so a dropdown left this column mostly empty air; this fills it and
    # keeps every model visible (and its role readable) without an extra click.
    model_name = st.session_state.setdefault("in_model", DEFAULT_MODEL)
    for _name in models.keys():
        if st.button(f":material/{MODEL_ICON[_name]}: {_name}", key=f"modelsel_{_name}",
                    width="stretch",
                    type=("primary" if _name == model_name else "secondary")):
            st.session_state["in_model"] = _name
            st.rerun()
    st.caption(MODEL_ROLE[model_name])

with top2:
    st.markdown("**Test-set performance**")
    m = TEST_METRICS[model_name]
    mc1, mc2 = st.columns(2)
    mc1.metric("Accuracy", f"{m['Accuracy']:.1f}%")
    mc2.metric("Recall", f"{m['Recall']:.1f}%")
    mc3, mc4 = st.columns(2)
    mc3.metric("F1", f"{m['F1']:.1f}%")
    mc4.metric("AUC", f"{m['AUC']:.3f}")

with top3:
    st.markdown("**Demo presets**")
    for label in PRESETS:
        if st.button(label, width="stretch", key=f"preset_{label}"):
            p = PRESETS[label]
            for k, v in p.items():
                if k == "addons":
                    for c, val in v.items():
                        st.session_state[f"in_{c}"] = val
                else:
                    st.session_state[f"in_{k}"] = v
            st.session_state["in_auto_total_mode"] = "Auto"
            # Tell the browser-side profile cache this is an intentional
            # server override, not a stale default arriving after an edit.
            # Microseconds remain exactly representable in JavaScript while
            # still making consecutive preset overrides unambiguous.
            st.session_state["tower_3d_override_nonce"] = time.time_ns() // 1_000
            st.rerun()

model = models[model_name]

tab_pred, tab_analysis, tab_models = st.tabs(
    ["Predict", "Data Analysis", "Models"]
)

# ======================================================================
# TAB 1 — PREDICT
# ======================================================================
with tab_pred:
    # Widgets are deliberately NOT inside st.form: inside a form, a `disabled=`
    # flag derived from another in-form widget only updates after submit, so
    # toggling Internet Service to "No" would leave the add-ons looking "open"
    # (interactable) until the form is submitted. Live widgets keep every
    # relationship between inputs visible as they are edited.
    with st.expander("How these inputs relate to each other (read before entering data)", expanded=False):
        st.markdown("""
**Tenure ↔ Contract Type** — these are *correlated but not constrained*. `Contract` is the customer's
**current** contract, not a lifetime commitment. In the real data **1,144 customers are on
Month-to-month with tenure over 24 months**, and **142 are on a Two-year contract with under 24 months'
tenure** (they signed recently). So *any* contract is valid at *any* tenure — the app below shows you
how common your combination actually is.

**Tenure × Monthly Charges ↔ Total Charges** — `TotalCharges` is roughly the running total, so
`tenure × MonthlyCharges` is a very good estimate: in the real data the median deviation is **0.0%**,
the mean absolute deviation is **3.2%**, and **94.6% of customers fall within ±10%**. Deviations are
genuine — the customer's monthly price changed over time (upgrades, promotions). Leave
**Auto-calculate** on unless you are modelling a specific billing history.

**Internet Service ↔ Add-on Services** — in the dataset, all 1,526 customers without internet have
*"No internet service"* for all six add-ons, with **zero exceptions**. The add-ons below stay editable,
but if you set Internet Service to *"No"* the model input is coerced to match the dataset's encoding
(the app tells you when it does this). The same applies to Phone Service ↔ Multiple Lines.

**What the model actually consumes** — `tenure`, `MonthlyCharges`, `TotalCharges`, plus two engineered
features: `ContractRiskScore` (Month-to-month = 2, One year = 1, Two year = 0) and
`ChargesToTenureRatio` = `MonthlyCharges / (tenure + 1)`.
        """)

    st.markdown('<div class="grp">Customer profile</div>', unsafe_allow_html=True)

    # The 3D tower and both profile zones share one full-width component.
    network_panel = st.container(key="customer_network")

    with network_panel:
        st.markdown(
            '<div class="tower-title">Interactive customer network</div>',
            unsafe_allow_html=True,
        )
        tenure = st.session_state.setdefault("in_tenure", 12)
        monthly_charges = st.session_state.get("in_monthly", 70.0)
        _tenure_level = int(pd.cut([tenure], [-1, 12, 24, 48, 60, 200], labels=[1, 2, 3, 4, 5])[0])
        _tier_label, _gradient = TIER_INFO[_tenure_level]
        st.caption(f":material/military_tech: {_tier_label} member · {tenure} mo tenure")

        st.caption("Hover to pause the 3D tower, then select an attached equipment pod.")

        # Every value lives in session_state so switching category changes only
        # what is visible, never the profile already entered.
        contract = st.session_state.setdefault("in_contract", "Month-to-month")
        payment_method = st.session_state.setdefault("in_payment", "Electronic check")
        paperless_billing = st.session_state.setdefault("in_paperless", "No")
        phone_service = st.session_state.setdefault("in_phone", "Yes")
        internet_service = st.session_state.setdefault("in_internet", "DSL")
        multiple_lines = st.session_state.setdefault("in_lines", "No")
        gender = st.session_state.setdefault("in_gender", "Female")
        senior_citizen = st.session_state.setdefault("in_senior", "No")
        partner = st.session_state.setdefault("in_partner", "No")
        dependents = st.session_state.setdefault("in_dependents", "No")
        auto_mode = st.session_state.setdefault("in_auto_total_mode", "Auto")
        manual_total = st.session_state.setdefault(
            "in_total_manual", float(round(tenure * monthly_charges, 2))
        )
        addon_vals = {
            svc: st.session_state.setdefault(f"in_{svc}", "No")
            for svc in ADDON_SERVICES
        }
        tower_values = render_tower_3d({
            "in_gender": gender,
            "in_senior": senior_citizen,
            "in_partner": partner,
            "in_dependents": dependents,
            "in_monthly": monthly_charges,
            "in_auto_total_mode": auto_mode,
            "in_total_manual": manual_total,
            "in_tenure": tenure,
            "in_contract": contract,
            "in_payment": payment_method,
            "in_paperless": paperless_billing,
            "in_phone": phone_service,
            "in_internet": internet_service,
            "in_lines": multiple_lines,
            **{f"in_{service}": value for service, value in addon_vals.items()},
        })
        gender = tower_values["in_gender"]
        senior_citizen = tower_values["in_senior"]
        partner = tower_values["in_partner"]
        dependents = tower_values["in_dependents"]
        monthly_charges = tower_values["in_monthly"]
        auto_mode = tower_values["in_auto_total_mode"]
        manual_total = tower_values["in_total_manual"]
        tenure = tower_values["in_tenure"]
        contract = tower_values["in_contract"]
        payment_method = tower_values["in_payment"]
        paperless_billing = tower_values["in_paperless"]
        phone_service = tower_values["in_phone"]
        internet_service = tower_values["in_internet"]
        multiple_lines = tower_values["in_lines"]
        addon_vals = {service: tower_values[f"in_{service}"] for service in ADDON_SERVICES}

    # Total Charges is edited and explained inside the Charges tower section.
    # Auto mode remains a derived model input; Manual mode uses the cached value.
    expected_total = round(tenure * monthly_charges, 2)
    total_charges = float(expected_total if auto_mode == "Auto" else manual_total)

    # --- Services -------------------------------------------------------------
    # Connection and add-on values are edited in the selected tower control dock;
    # the notices below explain any dataset-consistency coercion applied later.
    # Coercion notices — the add-ons stay editable, but the model input is made
    # consistent with the dataset's encoding, and the user is told when that happens.
    coerced = []
    if internet_service == "No":
        turned_on = [s for s, v in addon_vals.items() if v == "Yes"]
        if turned_on:
            coerced.append(
                f"Internet Service is <b>No</b>, so {len(turned_on)} add-on(s) "
                f"({', '.join(turned_on)}) are sent to the model as "
                f'<b>"No internet service"</b> — all 1,526 such customers in the dataset '
                "are encoded that way, with zero exceptions.")
    if phone_service == "No" and multiple_lines == "Yes":
        coerced.append('Phone Service is <b>No</b>, so Multiple Lines is sent as '
                       '<b>"No phone service"</b> (682 such customers, zero exceptions).')
    if coerced:
        st.markdown('<div class="finding amber">⚠️ ' + "<br>".join(coerced) + "</div>",
                    unsafe_allow_html=True)

    profile_snapshot = {
        "gender": gender, "senior_citizen": senior_citizen,
        "partner": partner, "dependents": dependents, "tenure": tenure,
        "contract": contract, "paperless_billing": paperless_billing,
        "payment_method": payment_method, "monthly_charges": float(monthly_charges),
        "total_charges": float(total_charges), "phone_service": phone_service,
        "multiple_lines": multiple_lines, "internet_service": internet_service,
        "addons": dict(addon_vals), "model_name": model_name,
    }

    # The button + result block runs as a fragment: clicking Predict only reruns this
    # function, not the whole script (Data Analysis / Models tab computations are
    # skipped), so the result appears snappily with no full-page flash — and the
    # smooth CSS/Plotly transitions below actually get a chance to play.
    @st.fragment
    def render_prediction(gender, senior_citizen, partner, dependents, tenure, contract,
                          paperless_billing, payment_method, monthly_charges, total_charges,
                          phone_service, multiple_lines, internet_service, addon_vals,
                          model_name, model, models, feature_columns, scaler,
                          profile_snapshot):
        predict_clicked = st.button(
            f"Predict Churn Risk  ·  {model_name}",
            width="stretch",
            type="primary",
            key="predict_button",
        )
        attach_predict_button_loader()

        if predict_clicked:
            eff_addons = dict(addon_vals)
            eff_lines = multiple_lines
            if internet_service == "No":
                eff_addons = {s: "No" for s in ADDON_SERVICES}
            if phone_service == "No":
                eff_lines = "No"

            raw_input = pd.DataFrame([{
                "customerID": "PROTOTYPE-INPUT", "gender": gender,
                "SeniorCitizen": 1 if senior_citizen == "Yes" else 0,
                "Partner": partner, "Dependents": dependents, "tenure": tenure,
                "PhoneService": phone_service, "MultipleLines": eff_lines,
                "InternetService": internet_service,
                "OnlineSecurity": eff_addons["OnlineSecurity"],
                "OnlineBackup": eff_addons["OnlineBackup"],
                "DeviceProtection": eff_addons["DeviceProtection"],
                "TechSupport": eff_addons["TechSupport"],
                "StreamingTV": eff_addons["StreamingTV"],
                "StreamingMovies": eff_addons["StreamingMovies"],
                "Contract": contract, "PaperlessBilling": paperless_billing,
                "PaymentMethod": payment_method, "MonthlyCharges": monthly_charges,
                "TotalCharges": total_charges, "Churn": "No",
            }])

            cleaned = engineer_and_clean(raw_input)
            X_input = build_feature_matrix_proto(cleaned).reindex(columns=feature_columns, fill_value=0)
            X_input_scaled = X_input.copy()
            X_input_scaled[NUM_COLS_TO_SCALE] = scaler.transform(X_input[NUM_COLS_TO_SCALE])

            proba = float(model.predict_proba(X_input_scaled)[0, 1])
            if proba < 0.40:
                risk_label, risk_color = "LOW RISK", GREEN
            elif proba < 0.70:
                risk_label, risk_color = "MEDIUM RISK", AMBER
            else:
                risk_label, risk_color = "HIGH RISK", RED

            all_probs = {
                name: float(candidate.predict_proba(X_input_scaled)[0, 1]) * 100
                for name, candidate in models.items()
            }
            st.session_state["last_prediction_summary"] = {
                "profile": profile_snapshot,
                "probability": proba * 100,
                "risk_label": risk_label,
                "risk_color": risk_color,
                "model_name": model_name,
                "all_probs": all_probs,
            }

            st.divider()
            st.subheader("Prediction Result")
            st.markdown(
                pv.hero_html(proba * 100, risk_label, risk_color, model_name),
                unsafe_allow_html=True,
            )
            st.plotly_chart(
                pv.signal_spectrum(proba * 100),
                width="stretch", config={"displayModeBar": False},
                key="prediction_signal_spectrum",
            )
            if risk_label == "LOW RISK":
                st.balloons()

            # Tenure x Contract plausibility — shown only now, as evidence *for* the
            # result above, not as a pre-prediction hint at what the answer will be.
            share, churn_ref, counts = contract_tenure_reference()
            tband = pd.cut([tenure], [-1, 12, 24, 48, 60, 200],
                           labels=["0-12", "13-24", "25-48", "49-60", "61+"])[0]
            pct_share = float(share.loc[tband, contract])
            n_cell = int(counts.loc[tband, contract])
            obs_churn = float(churn_ref.loc[tband, contract])
            common = share.loc[tband].idxmax()
            tone = "green" if pct_share >= 30 else ("amber" if pct_share >= 8 else "blue")
            st.markdown(
                f'<div class="finding {tone}">📌 <b>Tenure {tenure} months ({tband}) + {contract}</b> — '
                f'{pct_share:.1f}% of real customers in this tenure band hold this contract '
                f'(<b>{n_cell:,} customers</b>), and their observed churn rate is <b>{obs_churn:.1f}%</b>. '
                f'Most common contract in this band: <b>{common}</b>. '
                f'All combinations are valid — contract type is the current agreement, not a lifetime lock-in.</div>',
                unsafe_allow_html=True)

            # top contributing features
            st.markdown("##### Top factors influencing this prediction")
            if hasattr(model, "feature_importances_"):
                importances = pd.Series(model.feature_importances_, index=feature_columns)
                imp_col, imp_note = f"{model_name} Importance", (
                    f"Global feature importance for {model_name} (Section 5.3), "
                    "shown against this customer's value.")
            else:
                importances = pd.Series(np.abs(model.coef_[0]), index=feature_columns)
                imp_col, imp_note = f"{model_name} |Coefficient|", (
                    f"{model_name} has no feature_importances_; absolute standardised coefficient "
                    "shown instead (Section 5.4).")
            top_features = importances.sort_values(ascending=False).head(6)
            rows = []
            for feat in top_features.index:
                val = X_input.iloc[0][feat]
                rows.append({"Feature": feat, imp_col: round(top_features[feat], 3),
                             "This customer": round(val, 2) if isinstance(val, (int, float, np.integer, np.floating)) else val})
            st.dataframe(pd.DataFrame(rows), hide_index=True, width="stretch")
            st.caption(imp_note + " Global ranking, not a per-prediction SHAP explanation (future work).")

            st.markdown("##### Model consensus")
            st.caption("The star marks the selected model; hover each signal for test-set context.")
            st.plotly_chart(
                pv.model_consensus(all_probs, model_name, TEST_METRICS),
                width="stretch", config={"displayModeBar": False},
                key="prediction_model_consensus",
            )
            with st.expander("Show raw model input (debug)"):
                st.dataframe(X_input.T, width="stretch")
            # This delta reaches the browser after the result UI above, providing a
            # deterministic completion signal without relying on Streamlit's global
            # Running indicator (which fragments do not consistently render).
            finish_predict_button_loader()
        elif "last_prediction_summary" in st.session_state:
            cached = st.session_state["last_prediction_summary"]
            outdated = cached["profile"] != profile_snapshot
            if outdated:
                st.warning("Profile changed — click **Predict Churn Risk** to refresh this result.")
            else:
                st.caption("Showing the most recent prediction for the current profile.")
            st.divider()
            st.subheader("Prediction Result")
            st.markdown(
                pv.hero_html(cached["probability"], cached["risk_label"],
                             cached["risk_color"], cached["model_name"]),
                unsafe_allow_html=True,
            )
            st.plotly_chart(
                pv.signal_spectrum(cached["probability"]),
                width="stretch", config={"displayModeBar": False},
                key="cached_prediction_signal_spectrum",
            )
            st.markdown("##### Model consensus")
            st.plotly_chart(
                pv.model_consensus(cached["all_probs"], cached["model_name"], TEST_METRICS),
                width="stretch", config={"displayModeBar": False},
                key="cached_prediction_model_consensus",
            )
        else:
            st.info("Adjust the profile above, then click **Predict Churn Risk**. "
                    "Use the sidebar presets to jump to the highest- or lowest-risk segment "
                    "identified in the report.")

    render_prediction(gender, senior_citizen, partner, dependents, tenure, contract,
                      paperless_billing, payment_method, monthly_charges, total_charges,
                      phone_service, multiple_lines, internet_service, addon_vals,
                      model_name, model, models, feature_columns, scaler,
                      profile_snapshot)

# ======================================================================
# TAB 2 — DATA ANALYSIS  (report Sections 2-3, every analysis, computed live)
# ======================================================================
with tab_analysis:
    df_eda, X_full, y_full = load_eda_data()

    (da_overview, da_univariate, da_engineered, da_interact,
     da_stats, da_quality, da_vif) = st.tabs([
        "Overview", "Churn Patterns", "Feature Engineering",
        "Customer Interactions", "Statistical Evidence", "Data Quality", "Multicollinearity",
    ])

    # -- 2.1-2.3 Overview & summary statistics -------------------------
    with da_overview:
        sec("2.1-2.3", "Dataset Overview & Summary Statistics")
        o1, o2, o3, o4 = st.columns(4)
        o1.metric("Customers", f"{len(df_eda):,}")
        o2.metric("Original attributes", "21")
        o3.metric("Churn rate", f"{(df_eda['Churn']=='Yes').mean()*100:.1f}%")
        o4.metric("Avg tenure", f"{df_eda['tenure'].mean():.1f} mo")

        target_df = eda.target_distribution(df_eda)
        c1, c2 = st.columns([1, 2])
        with c1:
            st.markdown("**Target distribution (Table)**")
            st.dataframe(target_df, width="stretch")
        with c2:
            st.markdown("**Figure 1 — Target Distribution (Chart)**")
            st.plotly_chart(pc.plot_target_distribution_plotly(df_eda),
                            width="stretch", key="target_dist_chart")

        st.markdown("**Table 4 — Summary statistics for numerical features**")
        summary_cols = ["tenure", "MonthlyCharges", "TotalCharges", "SeniorCitizen"]
        st.dataframe(eda.summary_statistics(df_eda, summary_cols).style.format("{:.2f}"),
                     width="stretch")
        st.caption("Average tenure ~32 months with a std almost as large as the mean — a mix of "
                   "new and long-established customers, not a homogeneous base (Section 2.3).")

    # -- 2.5 Univariate & bivariate patterns ----------------------------
    with da_univariate:
        sec("2.5", "Univariate and Bivariate Churn Patterns")
        pick_col = st.selectbox(
            "Churn rate by category —  pick a feature",
            ["Contract", "InternetService", "PaymentMethod", "SeniorCitizen", "PaperlessBilling",
             "Partner", "Dependents", "gender", "TechSupport", "OnlineSecurity"],
            index=0,
        )
        u1, u2 = st.columns([1, 1])
        with u1:
            st.dataframe(eda.churn_rate_by_category(df_eda, pick_col), width="stretch")
        with u2:
            st.markdown(f"**Churn rate by {pick_col}**")
            st.plotly_chart(pc.plot_churn_rate_by_category_plotly(df_eda, pick_col),
                            width="stretch", key="churn_by_cat_chart")

        st.markdown("**All categorical features at once (Figure 2a)**")
        st.plotly_chart(pc.plot_churn_rate_small_multiples_plotly(df_eda),
                        width="stretch", key="small_multiples_chart")
        st.markdown(
            '<div class="finding">Month-to-month churns at <b>42.7%</b> vs <b>2.8%</b> for two-year '
            '(15x gap). Electronic-check (manual) payers churn at <b>45.3%</b> vs 15-17% for automatic '
            'methods (Section 2.5).</div>', unsafe_allow_html=True)

        st.markdown("**Numeric features by churn class — distributions (Figure 2b) & boxplots (Figure 2c)**")
        n1, n2 = st.columns(2)
        with n1:
            st.plotly_chart(pc.plot_numeric_distributions_by_churn_plotly(df_eda),
                            width="stretch", key="numeric_dist_chart")
        with n2:
            st.plotly_chart(pc.plot_numeric_boxplots_by_churn_plotly(df_eda),
                            width="stretch", key="numeric_box_chart")

    # -- 2.6 Engineered feature audit -----------------------------------
    with da_engineered:
        sec("2.6", "Engineered Feature Audit",
            "8 features were derived from the existing 21 columns; each is checked directly "
            "against the data rather than assumed useful.")

        e1, e2 = st.columns([1, 1])
        with e1:
            st.markdown("**Figure 4 — Correlation of numeric/engineered features with churn**")
            st.plotly_chart(pc.plot_correlation_with_target_plotly(df_eda, epl.CORR_COLS),
                            width="stretch", key="corr_target_chart")
        with e2:
            st.markdown("**Figure 4a — Correlation heatmap** (interactive — hover for exact r)")
            st.plotly_chart(pc.plot_correlation_heatmap_plotly(df_eda, epl.CORR_COLS),
                            width="stretch", key="corr_heatmap")
        st.markdown(
            '<div class="finding green"><b>ChargesToTenureRatio (r=0.412)</b> and '
            '<b>ContractRiskScore (r=0.397)</b> beat every raw numeric column — the direct, data-driven '
            'justification for keeping both in the model (Section 2.6.1).</div>', unsafe_allow_html=True)

        st.markdown("**Figure 3 — Churn rate by TenureGroup** (descriptive only, not modelled)")
        f1, f2 = st.columns([1, 1])
        with f1:
            st.dataframe(eda.churn_rate_by_category(df_eda, "TenureGroup"), width="stretch")
        with f2:
            st.plotly_chart(pc.plot_churn_rate_by_tenuregroup_plotly(df_eda),
                            width="stretch", key="tenuregroup_chart")

        st.markdown("**2.6.2 — TotalServicesSubscribed: a non-monotonic pattern**")
        st.dataframe(eda.churn_rate_by_category(df_eda, "TotalServicesSubscribed"), width="stretch")
        st.caption("Weak overall correlation (r = -0.067) and non-monotonic on its own — Section 2.7 "
                   "shows the real relationship only appears once tenure is held fixed.")

        with st.expander("Validation evidence for the 3 rejected engineered features"):
            audit = eda.validate_engineered_features(df_eda)
            st.markdown("**HasInternetService vs InternetService** — collapsing hides the Fiber-vs-DSL split:")
            st.json(audit["HasInternetService_vs_InternetService"])
            st.markdown("**HasPartnerOrDependents vs Partner alone** — adds nothing beyond Partner:")
            st.json(audit["HasPartnerOrDependents_vs_Partner"])
            st.markdown(f"**AvgChargePerMonth vs MonthlyCharges** correlation: "
                       f"`{audit['AvgChargePerMonth_vs_MonthlyCharges_corr']}` (near-perfect duplicate)")
            st.markdown(f"**TotalServicesSubscribed vs manual service-flag sum** correlation: "
                       f"`{audit['TotalServicesSubscribed_vs_manual_sum_corr']}` (exact duplicate, dropped from modelling)")

    # -- 2.7 Multivariate interactions -----------------------------------
    with da_interact:
        sec("2.7", "Multivariate Interaction Analysis",
            "Where the most actionable findings turned up — combinations that single-variable "
            "views (Section 2.5) cannot show.")
        i1, i2 = st.columns(2)
        with i1:
            st.markdown("**Figure 5 — Contract × payment automation**")
            st.plotly_chart(pc.plot_interaction_heatmap_plotly(
                df_eda, "Contract", "IsAutoPay",
                row_order=["Month-to-month", "One year", "Two year"]),
                width="stretch", key="contract_autopay_chart")
            st.markdown(
                '<div class="finding"><b>Month-to-month + manual pay = 46.5%</b>, the highest-risk '
                'segment in the dataset. Two-year churns at 2.8-2.9% regardless of payment method — '
                'contract commitment cancels out payment friction almost entirely.</div>',
                unsafe_allow_html=True)
        with i2:
            st.markdown("**Figure 5b — Tenure group × number of services**")
            st.plotly_chart(pc.plot_tenure_service_interaction_plotly(df_eda),
                            width="stretch", key="tenure_service_chart")
            st.markdown(
                '<div class="finding blue">Within <b>every</b> tenure band, churn <b>rises</b> with '
                'service count — the opposite of the raw pattern in 2.6.2. First-year customers with '
                '4-5 services peak at <b>56.9%</b> (early bill shock, not loyalty).</div>',
                unsafe_allow_html=True)

    # -- 2.8 Statistical association tests --------------------------------
    with da_stats:
        sec("2.8", "Statistical Association Tests",
            "Chi-square + Cramer's V for categoricals; point-biserial correlation for numerics — "
            "hypothesis testing rather than visual inspection alone.")
        chi_df = eda.chi_square_tests(df_eda, [c for c in epl.CHI_CAT_COLS if c in df_eda.columns])
        pb_df = eda.point_biserial_tests(df_eda, [c for c in epl.CORR_COLS if c in df_eda.columns])

        s1, s2 = st.columns([3, 2])
        with s1:
            st.markdown("**Table 6a — Chi-square test + Cramer's V (categorical features)**")
            st.dataframe(
                chi_df.style.format({"chi2": "{:.1f}", "p_value": "{:.2e}", "cramers_v": "{:.3f}"})
                    .background_gradient(cmap="Reds", subset=["cramers_v"]),
                hide_index=True, width="stretch", height=420)
        with s2:
            st.markdown("**Figure 5a — Cramer's V association strength**")
            st.plotly_chart(pc.plot_cramers_v_plotly(chi_df), width="stretch", key="cramers_v_chart")

        st.markdown(
            '<div class="finding">Every categorical feature rejects independence from churn at '
            'p&lt;0.05 <b>except gender (p=0.487) and PhoneService (p=0.339)</b> — statistically '
            'unrelated. Only Contract (V=0.410), InternetService (0.322) and PaymentMethod (0.303) '
            'reach a <b>moderate</b> association; the rest are weak or negligible.</div>',
            unsafe_allow_html=True)

        st.markdown("**Table 6b — Point-biserial correlation (numeric/engineered features)**")
        st.dataframe(
            pb_df.style.format({"point_biserial_r": "{:+.3f}", "p_value": "{:.2e}"})
                .background_gradient(cmap="RdBu_r", subset=["point_biserial_r"], vmin=-0.5, vmax=0.5),
            hide_index=True, width="stretch")

    # -- 3.1-3.2 Data quality & outliers ------------------------------------
    with da_quality:
        sec("3.1-3.2", "Data Quality: Missing Values, Invalid Values, Outliers, Duplicates")

        df_raw = dp.load_data()
        total_charges_numeric = pd.to_numeric(df_raw["TotalCharges"], errors="coerce")
        n_missing = int(total_charges_numeric.isna().sum())
        q1, q2, q3 = st.columns(3)
        q1.metric("Missing TotalCharges (after coerce)", n_missing)
        q2.metric("All missing have tenure = 0", "Yes" if (df_raw.loc[total_charges_numeric.isna(), "tenure"] == 0).all() else "No")
        q3.metric("Imputation method", "Fill 0 (logic-based)")
        st.caption("3.1 — Blank strings pass an initial isnull() check; pd.to_numeric(errors='coerce') "
                   "reveals the 11 true NaNs, all brand-new (tenure=0) customers imputed as 0, not the "
                   "population median/mean.")

        st.markdown("**3.2 — Invalid value check** (boolean filter for negative values)")
        num_cols_chk = ["tenure", "MonthlyCharges", "TotalCharges", "TotalServicesSubscribed",
                        "AvgChargePerMonth", "ChargesToTenureRatio"]
        st.dataframe(eda.check_invalid_values(df_eda, num_cols_chk), hide_index=True, width="stretch")

        st.markdown("**3.2 — Outlier detection (mean ± 3σ)**")
        outliers = eda.detect_outliers_zscore(df_eda, num_cols_chk)
        st.dataframe(pd.DataFrame(outliers).T, width="stretch")

        st.markdown("**ChargesToTenureRatio outlier profile** — noise or genuine signal?")
        st.dataframe(eda.profile_outlier_group(df_eda, "ChargesToTenureRatio", profile_cols=["tenure"]),
                     hide_index=True, width="stretch")
        st.markdown(
            '<div class="finding">248 records (3.52%) exceed the 3σ bound — almost all brand-new '
            'customers already paying a high rate, churning at <b>83.1%</b> vs 26.5% overall. '
            'A genuine high-risk signal, kept rather than removed (Section 3.2).</div>',
            unsafe_allow_html=True)

        st.markdown("**Duplicate rows / IDs**")
        st.json(eda.check_duplicate_rows(df_eda))

    # -- 3.3 Multicollinearity (VIF) -----------------------------------------
    with da_vif:
        sec("3.3", "Multicollinearity Check (VIF)",
            "Four rounds of redundancy removal, from a worst-case VIF of 2,346 down to ~20 "
            "(recomputed live on the final 23-predictor feature matrix).")
        vif_df = compute_vif_table(tuple(feature_columns))
        v1, v2 = st.columns([1, 1])
        with v1:
            st.markdown("**VIF table (all 23 predictors)**")
            st.dataframe(vif_df.style.format({"VIF": "{:.2f}"})
                        .background_gradient(cmap="Reds", subset=["VIF"]),
                       hide_index=True, width="stretch", height=520)
        with v2:
            st.markdown("**VIF chart — top 15 by value**")
            st.plotly_chart(pc.plot_vif_plotly(vif_df), width="stretch", key="vif_chart")
        st.markdown(
            f'<div class="finding">Final max VIF ≈ <b>{vif_df["VIF"].max():.1f}</b> '
            f'({vif_df.iloc[0]["feature"]}), down from a worst case of 2,346 partway through the '
            'four-round audit (Section 3.3). Residual 10-20 range reflects genuine, disclosed '
            'correlation among tenure/charges/InternetService.</div>', unsafe_allow_html=True)

# ======================================================================
# TAB 3 — MODELS  (report Sections 4-5, full evaluation suite, computed live)
# ======================================================================
with tab_models:
    X_train_sm, y_train_sm, X_test_scaled, y_test = build_eval_bundle(tuple(feature_columns))

    (mo_perf, mo_importance,
     mo_reliability, mo_threshold) = st.tabs([
        "Performance", "Explainability", "Reliability", "Decision Threshold",
    ])

    # -- 5.1/5.2/5.6 Integrated performance workspace ----------------------
    with mo_perf:
        sec(
            "5.1, 5.2 & 5.6",
            "Interactive Model Performance Lab",
            "Rank models by the metric that matters, then inspect ROC and Precision-Recall "
            "behaviour. All values come from the existing held-out test predictions.",
        )
        performance_view = st.segmented_control(
            "Analysis view",
            ["Metric Scorecard", "ROC / PR Curves"],
            default="Metric Scorecard",
            key="performance_analysis_view",
        ) or "Metric Scorecard"

        dummy = ev.dummy_baseline(X_train_sm, y_train_sm, X_test_scaled, y_test)
        results_df = ev.evaluate_all_models(models, X_test_scaled, y_test)

        if performance_view == "Metric Scorecard":
            metric = st.segmented_control(
                "Metric focus",
                ["Accuracy", "Precision", "Recall", "F1", "AUC"],
                default="F1",
                key="performance_metric_focus",
                help="Changing the metric changes only the ranking view; model predictions stay fixed.",
            ) or "F1"
            ranking = miv.performance_ranking_frame(results_df, metric)
            best_model = ranking.index[0]
            selected_rank = int(ranking.index.get_loc(model_name) + 1)
            best_value = float(ranking.iloc[0][metric])
            selected_value = float(results_df.loc[model_name, metric])
            metric_value = lambda value: f"{value:.3f}" if metric == "AUC" else f"{value * 100:.1f}%"

            p1, p2, p3 = st.columns(3)
            p1.metric(f"Best {metric}", best_model)
            p1.caption(metric_value(best_value))
            p2.metric("Selected model", model_name)
            p2.caption(f"{metric_value(selected_value)} · rank {selected_rank} of {len(ranking)}")
            p3.metric("Gap from leader", metric_value(best_value - selected_value))
            p3.caption("0 means the selected model leads this metric")

            st.markdown(f"**Interactive {metric} ranking**")
            st.plotly_chart(
                miv.plot_metric_ranking(results_df, metric, selected_model=model_name),
                width="stretch",
                key="performance_metric_ranking",
            )
            st.markdown(
                f'<div class="finding blue"><b>Metric finding.</b> {best_model} leads {metric} at '
                f'<b>{metric_value(best_value)}</b>. The globally selected {model_name} ranks '
                f'<b>#{selected_rank}</b> at {metric_value(selected_value)}. Change the metric above '
                'to show why “best model” depends on the decision objective.</div>',
                unsafe_allow_html=True,
            )

            with st.expander("Accuracy trap — compare against the dummy baseline"):
                d1, d2, d3, d4 = st.columns(4)
                d1.metric("Dummy Accuracy", f"{dummy['Accuracy']*100:.1f}%")
                d2.metric("Dummy Precision", f"{dummy['Precision']*100:.1f}%")
                d3.metric("Dummy Recall", f"{dummy['Recall']*100:.1f}%")
                d4.metric("Dummy F1", f"{dummy['F1']*100:.1f}%")
                st.caption(
                    "Section 5.1 — A majority-class dummy reaches competitive Accuracy but scores "
                    "0.0 on Precision, Recall and F1. Accuracy alone would therefore mislead."
                )

            with st.expander("Table 7 and Figure 8 — full original performance comparison"):
                st.markdown("**Table 7 — Accuracy / Precision / Recall / F1 / AUC (test set, n=1,409)**")
                st.dataframe(
                    (results_df * 100).assign(AUC=results_df["AUC"]).style
                        .format({"Accuracy": "{:.2f}", "Precision": "{:.2f}", "Recall": "{:.2f}",
                                "F1": "{:.2f}", "AUC": "{:.3f}"})
                        .highlight_max(axis=0, props=f"background-color:{LIGHT};font-weight:700;"),
                    width="stretch",
                )
                st.markdown("**Figure 8 — Model Performance Comparison**")
                st.plotly_chart(
                    pc.plot_model_comparison_plotly(results_df),
                    width="stretch",
                    key="model_comparison_chart",
                )
        else:
            curve_summary = miv.curve_summary_frame(models, X_test_scaled, y_test)
            selected_curve = curve_summary.loc[model_name]
            auc_winner = curve_summary["ROC-AUC"].idxmax()
            ap_winner = curve_summary["Average Precision"].idxmax()

            st.markdown(
                f'<div class="finding blue"><b>Selected-model emphasis:</b> {model_name} is shown '
                'with a stronger line; the other models remain visible for a fair comparison.</div>',
                unsafe_allow_html=True,
            )
            c1, c2, c3 = st.columns(3)
            c1.metric("Selected ROC-AUC", f'{selected_curve["ROC-AUC"]:.3f}')
            c1.caption(f'Leader: {auc_winner} ({curve_summary.loc[auc_winner, "ROC-AUC"]:.3f})')
            c2.metric("Selected Avg Precision", f'{selected_curve["Average Precision"]:.3f}')
            c2.caption(f'Leader: {ap_winner} ({curve_summary.loc[ap_winner, "Average Precision"]:.3f})')
            c3.metric("No-skill PR baseline", f"{float(np.mean(y_test)):.3f}")
            c3.caption("Observed churn prevalence in the test set")

            roc_col, pr_col = st.columns(2)
            with roc_col:
                st.markdown("**Figure 6 — ROC curves**")
                st.plotly_chart(
                    miv.plot_discrimination_curve(
                        models, X_test_scaled, y_test, "ROC", selected_model=model_name
                    ),
                    width="stretch",
                    key="roc_chart",
                )
            with pr_col:
                st.markdown("**Figure 11 — Precision-Recall curves**")
                st.plotly_chart(
                    miv.plot_discrimination_curve(
                        models, X_test_scaled, y_test, "PR", selected_model=model_name
                    ),
                    width="stretch",
                    key="pr_chart",
                )
            st.markdown(
                f'<div class="finding blue"><b>Curve finding.</b> ROC-AUC ranks {auc_winner} first, '
                f'while Average Precision ranks {ap_winner} first. PR is especially useful here because '
                'churn is the minority class; showing both prevents a one-metric claim from being '
                'overstated (Section 5.6).</div>',
                unsafe_allow_html=True,
            )
            with st.expander("View exact ROC-AUC and Average Precision values"):
                st.dataframe(curve_summary.style.format("{:.3f}").highlight_max(
                    axis=0, props=f"background-color:{LIGHT};font-weight:700;"
                ), width="stretch")

    # -- 5.3-5.5 Integrated model explainability workspace -------------------
    with mo_importance:
        sec(
            "5.3-5.5",
            "Interactive Model Explainability Lab",
            "Compare ensemble drivers or inspect the explanation exposed by the model selected "
            "above. Importance describes model reliance, not causal impact.",
        )
        explanation_view = st.segmented_control(
            "Explanation view",
            ["Cross-model Drivers", "Selected Model Detail"],
            default="Cross-model Drivers",
            key="explanation_analysis_view",
        ) or "Cross-model Drivers"

        rf_imp = ev.get_feature_importance(models["Random Forest"], feature_columns)
        xgb_imp = ev.get_feature_importance(models["XGBoost"], feature_columns)
        lr_coefs = ev.get_lr_coefficients(models["Logistic Regression"], feature_columns)

        if explanation_view == "Cross-model Drivers":
            overlap = miv.tree_importance_overlap(models, feature_columns, top_n=10)
            aligned_importance = miv.tree_importance_comparison_frame(
                models, feature_columns, top_n=12
            )
            e1, e2, e3 = st.columns(3)
            e1.metric("Random Forest leader", overlap["rf_leader"])
            e1.caption(f'{overlap["rf_value"]:.3f} importance')
            e2.metric("XGBoost leader", overlap["xgb_leader"])
            e2.caption(f'{overlap["xgb_value"]:.3f} importance')
            e3.metric("Shared top-10 drivers", f'{overlap["shared_count"]} of 10')
            e3.caption("Agreement is useful; disagreement reveals model-specific reasoning")

            st.markdown("**How the two ensemble models prioritise the strongest drivers**")
            st.plotly_chart(
                miv.plot_tree_importance_comparison(aligned_importance),
                width="stretch",
                key="tree_importance_comparison",
            )
            shared_text = ", ".join(overlap["shared_features"][:5])
            if overlap["shared_count"] > 5:
                shared_text += f' and {overlap["shared_count"] - 5} more'
            st.markdown(
                f'<div class="finding green"><b>Driver comparison.</b> Random Forest is led by '
                f'<b>{overlap["rf_leader"]}</b>, while XGBoost is led by '
                f'<b>{overlap["xgb_leader"]}</b>. Their top-10 lists share '
                f'<b>{overlap["shared_count"]}</b> features: {shared_text}. This shows both '
                'consensus and model-specific reliance without claiming causation.</div>',
                unsafe_allow_html=True,
            )
        else:
            explanation = miv.model_explanation_frame(
                models[model_name], feature_columns, model_name
            )
            leader = explanation.iloc[0]
            explanation_type = leader["Explanation type"]
            s1, s2, s3 = st.columns(3)
            s1.metric("Selected model", model_name)
            s1.caption("Controlled by the model cards above")
            s2.metric("Explanation type", explanation_type)
            s2.caption("Coefficient" if explanation_type == "Coefficient" else "Global feature importance")
            s3.metric("Strongest driver", leader["Feature"])
            s3.caption(
                f'{leader["Effect"]:+.3f} coefficient'
                if explanation_type == "Coefficient"
                else f'{leader["Magnitude"]:.3f} importance'
            )

            st.markdown(f"**Top drivers exposed by {model_name}**")
            st.plotly_chart(
                miv.plot_selected_model_explanation(explanation, model_name, top_n=12),
                width="stretch",
                key="selected_model_explanation",
            )
            if explanation_type == "Coefficient":
                direction_text = "increases" if leader["Effect"] > 0 else "decreases"
                detail = (
                    f'{leader["Feature"]} has the largest absolute standardised coefficient '
                    f'({leader["Effect"]:+.3f}) and {direction_text} the modelled churn log-odds.'
                )
            else:
                detail = (
                    f'{leader["Feature"]} has the highest global importance '
                    f'({leader["Magnitude"]:.3f}) in {model_name}.'
                )
            st.markdown(
                f'<div class="finding blue"><b>Selected-model explanation.</b> {detail} '
                'This identifies what the fitted model relies on; it does not prove that changing '
                'the feature will cause churn to change.</div>',
                unsafe_allow_html=True,
            )

        with st.expander("Original Figure 9 — Random Forest and XGBoost top-10 importance"):
            i1, i2 = st.columns(2)
            with i1:
                st.markdown("**Figure 9 — Random Forest top-10 importance**")
                st.plotly_chart(
                    pc.plot_feature_importance_plotly(rf_imp),
                    width="stretch",
                    key="rf_importance_chart",
                )
            with i2:
                st.markdown("**XGBoost top-10 importance**")
                st.plotly_chart(
                    pc.plot_feature_importance_plotly(xgb_imp),
                    width="stretch",
                    key="xgb_importance_chart",
                )

        with st.expander("Table 8 — Logistic Regression coefficients & odds ratios"):
            oc1, oc2 = st.columns(2)
            oc1.markdown("Top positive (higher churn odds)")
            oc1.dataframe(
                lr_coefs.head(8).style.format({"coefficient": "{:.3f}", "odds_ratio": "{:.3f}"}),
                width="stretch",
            )
            oc2.markdown("Top negative (lower churn odds)")
            oc2.dataframe(
                lr_coefs.tail(8).sort_values("coefficient").style.format(
                    {"coefficient": "{:.3f}", "odds_ratio": "{:.3f}"}
                ),
                width="stretch",
            )

        with st.expander("Figure 12 — Decision Tree structure (top 3 of 5 levels)"):
            show_fig(
                ev.plot_decision_tree_structure(
                    models["Decision Tree"], feature_columns, max_depth_display=3
                )
            )
            st.caption(
                "The root-node split is on a contract/charges-related feature before any demographic "
                "attribute — a rule-based echo of the Section 2.7 interaction finding."
            )

    # -- 4.3/5.8 Integrated model reliability workspace --------------------
    with mo_reliability:
        sec(
            "4.3 & 5.8",
            "Interactive Model Reliability Lab",
            "Separate two reliability questions: the train-to-test generalisation gap and "
            "performance stability across five stratified folds.",
        )
        reliability_view = st.segmented_control(
            "Reliability view",
            ["Generalisation Gap", "Cross-Validation Stability"],
            default="Generalisation Gap",
            key="reliability_analysis_view",
        ) or "Generalisation Gap"

        overfit_df = ev.overfitting_check(models, X_train_sm, y_train_sm, X_test_scaled, y_test)

        if reliability_view == "Generalisation Gap":
            selected_gap = overfit_df.loc[model_name]
            closest_model = overfit_df["Gap"].abs().idxmin()
            widest_model = overfit_df["Gap"].idxmax()
            r1, r2, r3 = st.columns(3)
            r1.metric("Selected train F1", f'{selected_gap["Train F1"]:.3f}')
            r1.caption("Measured on the SMOTE-balanced training set")
            r2.metric("Selected test F1", f'{selected_gap["Test F1"]:.3f}')
            r2.caption("Measured on the natural held-out test set")
            r3.metric("Generalisation gap", f'{selected_gap["Gap"]:+.3f}')
            r3.caption(f'Closest train/test values: {closest_model}')

            st.markdown("**Train-to-test F1 movement for all four models**")
            st.plotly_chart(
                miv.plot_generalisation_dumbbell(overfit_df, selected_model=model_name),
                width="stretch",
                key="generalisation_dumbbell",
            )
            st.markdown(
                f'<div class="finding blue"><b>Generalisation finding.</b> The selected '
                f'{model_name} changes from train F1 <b>{selected_gap["Train F1"]:.3f}</b> to '
                f'test F1 <b>{selected_gap["Test F1"]:.3f}</b>, a gap of '
                f'<b>{selected_gap["Gap"]:+.3f}</b>. {widest_model} has the widest positive gap '
                f'({overfit_df.loc[widest_model, "Gap"]:+.3f}). Train and test distributions differ, '
                'so this is evidence to discuss—not a standalone proof of overfitting.</div>',
                unsafe_allow_html=True,
            )
            with st.expander("Original overfitting table and Figure 10"):
                oc1, oc2 = st.columns([1, 1])
                with oc1:
                    st.markdown("**Overfitting table**")
                    st.dataframe(
                        overfit_df.style.format("{:.3f}").background_gradient(
                            cmap="Reds", subset=["Gap"]
                        ),
                        width="stretch",
                    )
                with oc2:
                    st.markdown("**Figure 10 — Train vs Test F1**")
                    st.plotly_chart(
                        pc.plot_overfit_check_plotly(overfit_df),
                        width="stretch",
                        key="overfit_chart",
                    )
                st.caption(
                    "The report's initial unconstrained Random Forest overfit severely "
                    "(train F1 0.999 vs test 0.584); regularised GridSearchCV settings reduced "
                    "that gap while improving test F1 (Sections 4.2 and 5.8)."
                )
        else:
            cv_df = compute_cv_results()
            cv_metric = st.segmented_control(
                "Cross-validation metric",
                ["Accuracy", "Precision", "Recall", "F1", "ROC-AUC"],
                default="F1",
                key="cv_metric_focus",
            ) or "F1"
            cv_ranking = miv.cv_ranking_frame(cv_df, cv_metric)
            selected_cv = cv_ranking.loc[model_name]
            cv_leader = cv_ranking.index[0]
            most_stable = cv_ranking["Std"].idxmin()
            selected_rank = int(cv_ranking.index.get_loc(model_name) + 1)

            v1, v2, v3 = st.columns(3)
            v1.metric("Selected CV mean", f'{selected_cv["Mean"] * 100:.1f}%')
            v1.caption(f'{cv_metric} · rank {selected_rank} of {len(cv_ranking)}')
            v2.metric("Fold-to-fold SD", f'{selected_cv["Std"] * 100:.1f} pp')
            v2.caption(f'Lowest variability: {most_stable}')
            v3.metric(f"Best mean {cv_metric}", cv_leader)
            v3.caption(f'{cv_ranking.loc[cv_leader, "Mean"] * 100:.1f}%')

            st.markdown(f"**Five-fold {cv_metric} mean and variability**")
            st.plotly_chart(
                miv.plot_cv_stability(cv_df, cv_metric, selected_model=model_name),
                width="stretch",
                key="cv_stability_chart",
            )
            st.markdown(
                f'<div class="finding green"><b>Cross-validation finding.</b> {cv_leader} has '
                f'the highest mean {cv_metric} at '
                f'<b>{cv_ranking.loc[cv_leader, "Mean"] * 100:.1f}%</b>. The selected '
                f'{model_name} ranks <b>#{selected_rank}</b> with '
                f'{selected_cv["Mean"] * 100:.1f}% ± {selected_cv["Std"] * 100:.1f} pp. '
                f'{most_stable} has the lowest fold-to-fold standard deviation for this metric. '
                'SMOTE is applied inside each fold to avoid synthetic-sample leakage.</div>',
                unsafe_allow_html=True,
            )
            with st.expander("Original Section 4.3 cross-validation results table"):
                st.dataframe(cv_df.style.format("{:.3f}"), width="stretch")
                st.caption(
                    "Cross-validated means can be compared with the hold-out results to judge "
                    "whether the final ranking depends heavily on one train/test split."
                )

    # -- 5.7 Threshold tuning ------------------------------------------------------
    @st.fragment
    def render_threshold_tab(models, X_test_scaled, y_test, selected_model_name):
        sec(
            "5.2 & 5.7",
            "Interactive Error & Threshold Lab",
            "Compare all four models at the common 0.50 threshold, or explore how the selected "
            "model converts existing churn probabilities into decisions. No model is retrained.",
        )

        mode_col, values_col = st.columns([2, 1])
        with mode_col:
            analysis_mode = st.segmented_control(
                "Analysis mode",
                ["Selected Model", "Compare All Models"],
                default="Selected Model",
                key="threshold_analysis_mode",
                help="Use a fixed 0.50 threshold for a fair four-model comparison, or explore one model interactively.",
            ) or "Selected Model"
        with values_col:
            display_mode = st.segmented_control(
                "Values",
                ["Counts", "Percentages"],
                default="Counts",
                key="threshold_display_mode",
            ) or "Counts"

        if analysis_mode == "Compare All Models":
            comparison = miv.all_model_confusion_frame(models, X_test_scaled, y_test, threshold=0.50)
            winners = miv.all_model_winners(comparison)
            sample_size = int(comparison.iloc[0][["TN", "FP", "FN", "TP"]].sum())

            st.markdown(
                f'<div class="finding blue"><b>Fair comparison at threshold 0.50.</b><br>'
                f'<span style="opacity:.78">Every model is evaluated on the same {sample_size:,} held-out '
                'customers. Stars mark the best outcome within each error category; the outlined '
                'bars identify the model selected above.</span></div>',
                unsafe_allow_html=True,
            )

            w1, w2, w3 = st.columns(3)
            w1.metric("Fewest missed churners", winners["lowest_fn_model"])
            w1.caption(f'{winners["lowest_fn"]:,} false negatives')
            w2.metric("Fewest false alerts", winners["lowest_fp_model"])
            w2.caption(f'{winners["lowest_fp"]:,} false positives')
            w3.metric("Highest F1-score", winners["highest_f1_model"])
            w3.caption(f'{winners["highest_f1"] * 100:.1f}% F1 at threshold 0.50')

            st.markdown("**How the four models make different mistakes**")
            st.plotly_chart(
                miv.plot_all_model_error_comparison(
                    comparison,
                    display=display_mode,
                    selected_model=selected_model_name,
                ),
                width="stretch",
                key="all_model_error_comparison",
            )
            st.markdown(
                f'<div class="finding green"><b>Comparison finding.</b> '
                f'{winners["lowest_fn_model"]} misses the fewest churners '
                f'(<b>{winners["lowest_fn"]:,} FN</b>) and catches the most '
                f'(<b>{winners["highest_tp"]:,} TP</b>), while '
                f'{winners["lowest_fp_model"]} creates the fewest false alerts '
                f'(<b>{winners["lowest_fp"]:,} FP</b>). '
                f'{winners["highest_f1_model"]} retains the strongest F1 balance '
                f'(<b>{winners["highest_f1"] * 100:.1f}%</b>).</div>',
                unsafe_allow_html=True,
            )

            with st.expander("View exact confusion counts and rates for all models"):
                comparison_table = miv.all_model_comparison_table(comparison, display=display_mode)
                if display_mode == "Percentages":
                    table_style = comparison_table.style.format("{:.1f}")
                else:
                    table_style = comparison_table.style.format(
                        {
                            "FN": "{:,}", "FP": "{:,}", "TP": "{:,}", "TN": "{:,}",
                            "Precision": "{:.1%}", "Recall": "{:.1%}", "F1": "{:.1%}",
                        }
                    )
                st.dataframe(table_style, width="stretch")
                st.caption(
                    "Percentages are class-normalised: FN and TP use all actual churners as the "
                    "denominator; FP uses all actual retained customers. Report Section 5.2."
                )
            return

        st.markdown(
            f'<div class="finding blue"><b>Currently exploring: '
            f'{selected_model_name}</b><br><span style="opacity:.78">Use the model cards '
            f'above to change the model across the application.</span></div>',
            unsafe_allow_html=True,
        )

        model = models[selected_model_name]
        probabilities = miv.probability_vector(model, X_test_scaled)
        opt = ev.optimal_threshold(model, X_test_scaled, y_test)

        explore_thr = st.slider(
            "Classification threshold",
            0.10,
            0.90,
            float(opt["threshold"]),
            step=0.02,
            key="explore_thr",
            help="Lower values flag more customers as churn risks; higher values are more selective.",
        )

        default_snapshot = miv.threshold_snapshot(y_test, probabilities, 0.50)
        selected_snapshot = miv.threshold_snapshot(y_test, probabilities, explore_thr)
        sweep = miv.threshold_series(y_test, probabilities)

        st.markdown("**Live operating-point results**")
        m1, m2, m3, m4, m5 = st.columns(5)
        m1.metric(
            "Precision",
            f"{selected_snapshot['precision'] * 100:.1f}%",
            f"{(selected_snapshot['precision'] - default_snapshot['precision']) * 100:+.1f} pp vs 0.50",
        )
        m2.metric(
            "Recall",
            f"{selected_snapshot['recall'] * 100:.1f}%",
            f"{(selected_snapshot['recall'] - default_snapshot['recall']) * 100:+.1f} pp vs 0.50",
        )
        m3.metric(
            "F1-score",
            f"{selected_snapshot['f1'] * 100:.1f}%",
            f"{(selected_snapshot['f1'] - default_snapshot['f1']) * 100:+.1f} pp vs 0.50",
        )
        m4.metric(
            "False negatives",
            f"{selected_snapshot['fn']:,}",
            f"{selected_snapshot['fn'] - default_snapshot['fn']:+,} vs 0.50",
            delta_color="inverse",
            help="Actual churners predicted as retained — the missed-churn cases.",
        )
        m5.metric(
            "Customers flagged",
            f"{selected_snapshot['predicted_churn']:,}",
            f"{selected_snapshot['predicted_churn'] - default_snapshot['predicted_churn']:+,} vs 0.50",
            delta_color="off",
        )

        visual_mode = st.segmented_control(
            "Error view",
            ["Confusion Matrix", "Prediction Flow"],
            default="Confusion Matrix",
            key="threshold_visual_mode",
            help="Both views contain the same predictions. The flow view emphasises where customers move.",
        ) or "Confusion Matrix"

        chart_col, compare_col = st.columns([1.55, 1])
        with chart_col:
            if visual_mode == "Prediction Flow":
                st.markdown("**Actual-to-predicted customer flow**")
                st.plotly_chart(
                    miv.plot_confusion_sankey(selected_snapshot, display_mode),
                    width="stretch",
                    key="threshold_sankey",
                )
            else:
                st.markdown("**Confusion matrix at the selected threshold**")
                st.plotly_chart(
                    miv.plot_confusion_matrix(selected_snapshot, display_mode),
                    width="stretch",
                    key="threshold_confusion_matrix",
                )
        with compare_col:
            st.markdown("**Default vs selected**")
            st.dataframe(
                miv.comparison_frame(default_snapshot, selected_snapshot),
                hide_index=True,
                width="stretch",
            )
            st.markdown(
                f'<div class="finding blue"><b>Decision trade-off.</b> At threshold '
                f'<b>{explore_thr:.2f}</b>, {selected_model_name} catches '
                f'<b>{selected_snapshot["tp"]:,}</b> churners and misses '
                f'<b>{selected_snapshot["fn"]:,}</b>. Compared with 0.50, this is '
                f'<b>{selected_snapshot["fn"] - default_snapshot["fn"]:+,}</b> missed cases and '
                f'<b>{selected_snapshot["fp"] - default_snapshot["fp"]:+,}</b> false alerts.</div>',
                unsafe_allow_html=True,
            )

        st.markdown("**How the operating trade-off changes across thresholds**")
        st.plotly_chart(
            miv.plot_threshold_tradeoff_2d(sweep, explore_thr, selected_model_name),
            width="stretch",
            key="threshold_tradeoff_2d",
        )
        st.caption(
            f"The F1-optimal threshold for {selected_model_name} on this held-out test set is "
            f"{opt['threshold']:.2f}. Lower thresholds usually improve Recall by accepting more "
            "false alerts; the trained model and its probabilities remain unchanged."
        )

        with st.expander("Advanced interactive view — explore the trade-off in 3D"):
            st.caption(
                "Rotate or zoom the curve. Threshold is on the x-axis, Precision and Recall form "
                "the other two axes, colour represents F1-score, and the red point is your selection."
            )
            st.plotly_chart(
                miv.plot_threshold_tradeoff_3d(sweep, explore_thr, selected_model_name),
                width="stretch",
                key="threshold_tradeoff_3d",
            )

    with mo_threshold:
        render_threshold_tab(models, X_test_scaled, y_test, model_name)

st.divider()
st.caption(
    "Four models trained on 23 predictors after a four-round multicollinearity audit "
    "(Section 3.3 of the report): Logistic Regression, Decision Tree, Random Forest, XGBoost. "
    "Random Forest is the recommended default (Section 5.9) — test-set Accuracy 75.9%, "
    "Precision 53.3%, Recall 73.3%, F1 61.7%, AUC 0.839. Data Analysis and Models tabs run every "
    "report analysis live against the src/ package — this is not a static screenshot."
)
