"""
app.py — Telco Customer Churn Prediction Prototype (Section 6 of the report)

Run with:  streamlit run app.py   (from this folder)
       or:  streamlit run streamlit/app.py   (from the project root)

Requires models.pkl, scaler.pkl, feature_columns.pkl in this folder
(generated by running `python train_model.py` once beforehand).

Three tabs:
  * Predict        — enter a customer profile, get a churn probability + risk tier
  * Data Analysis   — every EDA / data-preparation analysis from report Sections 2-3,
                       computed live from the raw dataset via the src/ analysis package
  * Models          — the full modelling / evaluation suite from report Sections 4-5,
                       computed live against the deployed models
"""

import os
import sys
import pickle

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

_HERE = os.path.dirname(os.path.abspath(__file__))
_SRC = os.path.abspath(os.path.join(_HERE, "..", "src"))
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

from train_model import (  # noqa: E402  (local prototype module, mirrors src/data_prep.py)
    engineer_and_clean,
    build_feature_matrix as build_feature_matrix_proto,
    NUM_COLS_TO_SCALE,
    RAW_CSV_PATH,
)
import data_prep as dp  # noqa: E402
import eda  # noqa: E402
import eda_plots as epl  # noqa: E402
import modelling as md  # noqa: E402
import evaluation as ev  # noqa: E402
import plotly_charts as pc  # Plotly (interactive) chart layer — app-only, see file docstring
from sklearn.linear_model import LogisticRegression  # noqa: E402
from sklearn.tree import DecisionTreeClassifier  # noqa: E402
from sklearn.ensemble import RandomForestClassifier  # noqa: E402
from xgboost import XGBClassifier  # noqa: E402

DEFAULT_MODEL = "Random Forest"  # recommended model, report Section 5.9

# Report palette (Section colours) — shared with eda_plots.py / evaluation.py
NAVY, BLUE, LIGHT, RED = "#1F4E79", "#2E75B6", "#9DC3E6", "#C00000"
GREEN, AMBER = "#2E8B57", "#E8A317"

# Hold-out test metrics (report Section 5.2) — cross-checked against models.pkl
# on the true test split; kept as a display cache so the Predict-tab sidebar
# doesn't have to rerun evaluation on every widget interaction.
TEST_METRICS = {
    "Logistic Regression": dict(Accuracy=75.23, Precision=52.44, Recall=71.93, F1=60.65, AUC=0.833),
    "Decision Tree":       dict(Accuracy=73.74, Precision=50.35, Recall=77.01, F1=60.89, AUC=0.823),
    "Random Forest":       dict(Accuracy=75.87, Precision=53.31, Recall=73.26, F1=61.71, AUC=0.839),
    "XGBoost":             dict(Accuracy=75.23, Precision=52.40, Recall=72.99, F1=61.01, AUC=0.830),
}
MODEL_ROLE = {
    "Logistic Regression": "Linear baseline — interpretable coefficients, fast, the reference model.",
    "Decision Tree": "Single readable if-then tree — fully transparent, highest recall (77%).",
    "Random Forest": "200-tree bagged ensemble — best overall (recommended default).",
    "XGBoost": "Gradient-boosted ensemble — strong, regularised via GridSearchCV.",
}

ADDON_SERVICES = ["OnlineSecurity", "OnlineBackup", "DeviceProtection",
                  "TechSupport", "StreamingTV", "StreamingMovies"]
CONTRACT_RISK = {"Month-to-month": 2, "One year": 1, "Two year": 0}

# Demo presets — grounded in the report's findings (Sections 2.5 / 2.7)
PRESETS = {
    "🔥 Highest-risk segment": dict(
        gender="Female", senior="No", partner="No", dependents="No", tenure=2,
        contract="Month-to-month", paperless="Yes", payment="Electronic check",
        monthly=95.0, phone="Yes", lines="No", internet="Fiber optic",
        addons={c: "No" for c in ADDON_SERVICES}),
    "🛡️ Lowest-risk segment": dict(
        gender="Male", senior="No", partner="Yes", dependents="Yes", tenure=68,
        contract="Two year", paperless="No", payment="Credit card (automatic)",
        monthly=62.0, phone="Yes", lines="Yes", internet="DSL",
        addons={c: "Yes" for c in ADDON_SERVICES}),
    "📊 Dataset average": dict(
        gender="Female", senior="No", partner="No", dependents="No", tenure=32,
        contract="Month-to-month", paperless="Yes", payment="Electronic check",
        monthly=64.5, phone="Yes", lines="No", internet="Fiber optic",
        addons={c: "No" for c in ADDON_SERVICES}),
}

st.set_page_config(page_title="Telco Churn Predictor", page_icon="📡", layout="wide",
                   initial_sidebar_state="expanded")

# ----------------------------------------------------------------------
# Styling
# ----------------------------------------------------------------------
st.markdown(f"""
<style>
  /* Reduce top padding / space */
  .block-container {{
      padding-top: 1.5rem !important;
      padding-bottom: 0rem !important;
  }}
  [data-testid="stSidebarUserContent"] {{
      padding-top: 1.5rem !important;
  }}
  [data-testid="stHeader"] {{
      height: 2rem !important;
      background: transparent !important;
  }}

  /* Dynamic Background */
  .stApp {{
      background: radial-gradient(circle at 15% 50%, rgba(64, 156, 255, 0.08), transparent 40%),
                  radial-gradient(circle at 85% 30%, rgba(255, 105, 180, 0.08), transparent 40%);
      background-attachment: fixed;
  }}
  
  /* Apple Glassmorphism Banner */
  .app-banner {{
    background: color-mix(in srgb, var(--primary-color) 12%, transparent);
    backdrop-filter: blur(20px);
    -webkit-backdrop-filter: blur(20px);
    border: 1px solid color-mix(in srgb, var(--text-color) 8%, transparent);
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.04);
    color: var(--text-color);
    padding: 24px 32px; 
    border-radius: 24px; /* Squircle */
    margin-bottom: 12px;
  }}
  .app-banner .t {{ font-size: 1.8rem; font-weight: 800; letter-spacing:-0.5px; }}
  .app-banner .s {{ opacity:.75; font-size:1.0rem; margin-top:6px; font-weight: 400; }}
  
  /* Buttons */
  .stButton > button {{
      border-radius: 16px !important; /* Squircle */
      backdrop-filter: blur(10px);
      -webkit-backdrop-filter: blur(10px);
      transition: all 0.2s ease-in-out;
  }}
  .stButton > button:hover {{
      transform: scale(1.02);
  }}

  /* Inputs (Squircles) */
  .stSelectbox > div > div, 
  .stTextInput > div > div, 
  .stNumberInput > div > div,
  .stSlider > div > div {{
      border-radius: 16px !important;
  }}

  /* Metric Cards */
  [data-testid="stMetric"] {{
      background: color-mix(in srgb, var(--background-color) 40%, transparent);
      backdrop-filter: blur(16px);
      -webkit-backdrop-filter: blur(16px);
      border: 1px solid color-mix(in srgb, var(--text-color) 8%, transparent);
      border-radius: 20px;
      padding: 16px 20px;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.02);
  }}
  div[data-testid="stMetricValue"] {{ color: var(--text-color); font-weight: 700; letter-spacing: -0.5px; }}
  
  /* Sidebar */
  [data-testid="stSidebar"] {{
      background: color-mix(in srgb, var(--secondary-background-color) 60%, transparent) !important;
      backdrop-filter: blur(30px);
      -webkit-backdrop-filter: blur(30px);
      border-right: 1px solid color-mix(in srgb, var(--text-color) 8%, transparent);
  }}

  /* DataFrames */
  [data-testid="stDataFrame"] {{
      border-radius: 16px !important;
      overflow: hidden;
      border: 1px solid color-mix(in srgb, var(--text-color) 8%, transparent);
  }}

  /* Badges & Gauges */
  .risk-badge {{ display:inline-block; padding:10px 24px; border-radius:16px;
    font-weight:700; font-size:1.15rem; color:#fff; letter-spacing:.2px;
    box-shadow: 0 4px 16px rgba(0,0,0,0.1); }}
  .gauge {{ height:16px; background: color-mix(in srgb, var(--text-color) 10%, transparent); 
    border-radius:16px; overflow:hidden; margin:8px 0 4px; }}
  .gauge-fill {{ height:100%; border-radius:16px; transition:width 0.6s cubic-bezier(0.2, 0.8, 0.2, 1); }}
  
  /* Glass Findings */
  .finding {{ border-left: 6px solid {RED}; background:{RED}15; border-radius: 0 20px 20px 0;
    backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px);
    padding:16px 20px; margin:12px 0; box-shadow: 0 4px 20px rgba(0,0,0,0.02); }}
  .finding.blue {{ border-left-color:{BLUE}; background:{BLUE}15; }}
  .finding.green {{ border-left-color:{GREEN}; background:{GREEN}15; }}
  
  .secnote {{ color: var(--text-color); opacity: 0.6; font-size:.95rem; margin:-4px 0 12px; }}
  .stTabs [data-baseweb="tab"] {{ font-size:1.05rem; font-weight:600; border-radius: 12px 12px 0 0; }}

  /* Chart entrance animation — every Plotly AND matplotlib figure fades/slides in on
     first render, so switching tabs or triggering a recompute feels alive rather than
     a static image just appearing. */
  [data-testid="stPlotlyChart"], [data-testid="stImage"] {{
      animation: fadeSlideIn 0.6s ease-out;
  }}
  @keyframes fadeSlideIn {{
      from {{ opacity: 0; transform: translateY(14px); }}
      to   {{ opacity: 1; transform: translateY(0); }}
  }}

  /* High-risk badge pulses to draw the eye; low/medium stay static (calmer states) */
  .risk-badge.pulse {{ animation: pulseGlow 1.6s ease-in-out infinite; }}
  @keyframes pulseGlow {{
      0%, 100% {{ box-shadow: 0 4px 16px rgba(192,0,0,0.25); transform: scale(1); }}
      50%      {{ box-shadow: 0 4px 28px rgba(192,0,0,0.55); transform: scale(1.03); }}
  }}

  /* Finding callouts slide in from the left */
  .finding {{ animation: slideInLeft 0.5s ease-out; }}
  @keyframes slideInLeft {{
      from {{ opacity: 0; transform: translateX(-10px); }}
      to   {{ opacity: 1; transform: translateX(0); }}
  }}
</style>
""", unsafe_allow_html=True)

st.markdown(
    '<div class="app-banner"><div class="t">📡 Telco Customer Churn Predictor</div>'
    '<div class="s">BMDS2003 · Group 6 · CRISP-DM prototype — predict churn, explore every '
    'analysis behind the model, compare all four models</div></div>',
    unsafe_allow_html=True,
)


def sec(number, title, note=None):
    """Section header matching the report's numbering, so the app reads as a live
    companion to the write-up rather than a disconnected demo."""
    st.markdown(f"### {number}  {title}")
    if note:
        st.markdown(f'<p class="secnote">{note}</p>', unsafe_allow_html=True)


def show_fig(fig):
    st.pyplot(fig, width="stretch")
    plt.close(fig)


# ----------------------------------------------------------------------
# Cached loaders
# ----------------------------------------------------------------------
@st.cache_resource
def load_artifacts():
    """
    Loads the three trained-model artifacts this app depends on. This is the app's
    single external-file dependency (everything else is computed live from data/ via
    src/), so it's the one place worth a friendly failure message instead of a raw
    traceback — most likely to break during a live demo on a machine that hasn't run
    `python train_model.py` yet, or after a fresh git clone.
    """
    try:
        with open(os.path.join(_HERE, "models.pkl"), "rb") as f:
            models = pickle.load(f)
        with open(os.path.join(_HERE, "scaler.pkl"), "rb") as f:
            scaler = pickle.load(f)
        with open(os.path.join(_HERE, "feature_columns.pkl"), "rb") as f:
            feature_columns = pickle.load(f)
    except FileNotFoundError as e:
        st.error(
            "**Model artifacts not found.** This app needs `models.pkl`, `scaler.pkl`, "
            "and `feature_columns.pkl` in the `streamlit/` folder before it can run.\n\n"
            f"Missing file: `{os.path.basename(e.filename)}`\n\n"
            "Fix: open a terminal in the `streamlit/` folder and run:\n"
            "```\npython train_model.py\n```\n"
            "then reload this page."
        )
        st.stop()
    except Exception as e:
        st.error(
            f"**Could not load model artifacts** ({type(e).__name__}: {e}).\n\n"
            "This usually means the `.pkl` files were trained with a different library "
            "version than what's installed here. Fix: run `pip install -r requirement.txt` "
            "then `python train_model.py` again in the `streamlit/` folder, and reload this page."
        )
        st.stop()
    return models, scaler, feature_columns


@st.cache_data(show_spinner="Loading and preparing dataset...")
def load_eda_data():
    """Full EDA dataframe (all engineered features, for reporting) + the final
    23-predictor modelling matrix — the same src/data_prep.py pipeline the
    notebook and report use."""
    df_eda, X, y = dp.full_pipeline()
    return df_eda, X, y


@st.cache_data
def contract_tenure_reference():
    """
    How real customers distribute across Contract within each tenure band, plus the
    observed churn rate per (tenure band, contract) cell. Used by the Predict tab to
    tell the user how plausible their combination is — Contract is the customer's
    *current* contract, not a lifetime commitment, so every combination is legal,
    but they are far from equally common (Section 2.5).
    """
    df, _, _ = load_eda_data()
    d = df.copy()
    d["_tg"] = pd.cut(d["tenure"], [-1, 12, 24, 48, 60, 200],
                      labels=["0-12", "13-24", "25-48", "49-60", "61+"])
    d["_c"] = (d["Churn"] == "Yes").astype(int)
    share = pd.crosstab(d["_tg"], d["Contract"], normalize="index") * 100
    churn = d.pivot_table("_c", "_tg", "Contract", observed=True) * 100
    counts = pd.crosstab(d["_tg"], d["Contract"])
    return share.round(1), churn.round(1), counts


@st.cache_data
def charges_consistency_reference():
    """
    How closely TotalCharges tracks tenure x MonthlyCharges in the real data.
    Deviations are genuine (prices change over a customer's life), so the app uses
    this to tell the user whether a manually-entered TotalCharges is realistic.
    """
    df, _, _ = load_eda_data()
    d = df[df["tenure"] > 0].copy()
    expected = d["tenure"] * d["MonthlyCharges"]
    dev = (d["TotalCharges"] - expected) / expected * 100
    return {
        "median_dev": float(dev.median()),
        "p05": float(dev.quantile(0.05)),
        "p95": float(dev.quantile(0.95)),
        "within_10pct": float((dev.abs() <= 10).mean() * 100),
        "mean_abs_dev": float(dev.abs().mean()),
    }


@st.cache_resource(show_spinner="Reconstructing the train/test split and SMOTE resample...")
def build_eval_bundle(feature_columns):
    """
    Rebuilds the exact 80/20 stratified split, StandardScaler fit, and SMOTE
    resample used throughout the report (Sections 3.6-3.8), then aligns columns
    to the deployed models so the app can evaluate the *actual shipped* models
    (models.pkl) rather than retraining fresh ones.
    """
    df_eda, X, y = load_eda_data()
    X_train, X_test, y_train, y_test = md.split_data(X, y)
    X_train_scaled, X_test_scaled, _ = md.scale_features(X_train, X_test)
    X_train_sm, y_train_sm = md.resample_smote(X_train_scaled, y_train)
    X_test_scaled = X_test_scaled.reindex(columns=list(feature_columns), fill_value=0)
    X_train_sm = X_train_sm.reindex(columns=list(feature_columns), fill_value=0)
    return X_train_sm, y_train_sm, X_test_scaled, y_test


@st.cache_data(show_spinner="Running 5-fold stratified cross-validation (all four models)...")
def compute_cv_results():
    """Report Section 4.3 — fresh SMOTE per fold via an imblearn Pipeline, using the
    exact deployed hyperparameters (not re-run through GridSearchCV, for app speed)."""
    df_eda, X, y = load_eda_data()
    X_train, X_test, y_train, y_test = md.split_data(X, y)
    X_train_scaled, _, _ = md.scale_features(X_train, X_test)
    builders = {
        "Logistic Regression": LogisticRegression(max_iter=2000, random_state=42),
        "Decision Tree": DecisionTreeClassifier(max_depth=5, min_samples_split=10, random_state=42),
        "Random Forest": RandomForestClassifier(n_estimators=200, max_depth=12, min_samples_leaf=5, random_state=42),
        "XGBoost": XGBClassifier(max_depth=4, learning_rate=0.1, n_estimators=150, min_child_weight=10,
                                  subsample=0.8, colsample_bytree=0.8, reg_lambda=1,
                                  random_state=42, eval_metric="logloss"),
    }
    return ev.kfold_cv_all_models(X_train_scaled, y_train, builders)


@st.cache_data(show_spinner="Computing Variance Inflation Factors...")
def compute_vif_table(feature_columns):
    df_eda, X, y = load_eda_data()
    X = X.reindex(columns=list(feature_columns), fill_value=0)
    return eda.compute_vif(X.astype(float))


models, scaler, feature_columns = load_artifacts()

# ----------------------------------------------------------------------
# Sidebar — global model selector + context
# ----------------------------------------------------------------------
with st.sidebar:
    st.markdown("### ⚙️ Model")
    model_name = st.selectbox(
        "Prediction model", list(models.keys()),
        index=list(models.keys()).index(DEFAULT_MODEL),
        help="Random Forest is the recommended default (report Section 5.9). "
             "All four trained models are selectable for comparison.",
    )
    st.caption(MODEL_ROLE[model_name])

    m = TEST_METRICS[model_name]
    st.markdown("**Test-set performance**")
    sc1, sc2 = st.columns(2)
    sc1.metric("Accuracy", f"{m['Accuracy']:.1f}%")
    sc2.metric("Recall", f"{m['Recall']:.1f}%")
    sc3, sc4 = st.columns(2)
    sc3.metric("F1", f"{m['F1']:.1f}%")
    sc4.metric("AUC", f"{m['AUC']:.3f}")

    st.divider()
    st.markdown("### 🎬 Demo presets")
    st.caption("Load a profile grounded in the report's findings.")
    for label in PRESETS:
        if st.button(label, width="stretch", key=f"preset_{label}"):
            p = PRESETS[label]
            for k, v in p.items():
                if k == "addons":
                    for c, val in v.items():
                        st.session_state[f"in_{c}"] = val
                else:
                    st.session_state[f"in_{k}"] = v
            st.session_state["in_auto_total"] = True
            st.rerun()

    st.divider()
    st.caption(
        "23 predictors after a four-round multicollinearity audit (Section 3.3). "
        "SMOTE on the training set only; hyperparameters via 5-fold GridSearchCV."
    )
    st.caption("Data Analysis and Models tabs run every report analysis live from the src/ package.")

model = models[model_name]

tab_pred, tab_analysis, tab_models = st.tabs(
    ["🔮 Predict", "📊 Data Analysis", "🤖 Models"]
)

# ======================================================================
# TAB 1 — PREDICT
# ======================================================================
with tab_pred:
    # Widgets are deliberately NOT inside st.form: inside a form, a `disabled=`
    # flag derived from another in-form widget only updates after submit, so
    # toggling Internet Service to "No" would leave the add-ons looking "open"
    # (interactable) until the form is submitted. Live widgets keep every
    # relationship between inputs visible as they are edited.
    with st.expander("ℹ️  How these inputs relate to each other (read before entering data)", expanded=False):
        st.markdown("""
**Tenure ↔ Contract Type** — these are *correlated but not constrained*. `Contract` is the customer's
**current** contract, not a lifetime commitment. In the real data **1,144 customers are on
Month-to-month with tenure over 24 months**, and **142 are on a Two-year contract with under 24 months'
tenure** (they signed recently). So *any* contract is valid at *any* tenure — the app below shows you
how common your combination actually is.

**Tenure × Monthly Charges ↔ Total Charges** — `TotalCharges` is roughly the running total, so
`tenure × MonthlyCharges` is a very good estimate: in the real data the median deviation is **0.0%**,
the mean absolute deviation is **3.2%**, and **94.6% of customers fall within ±10%**. Deviations are
genuine — the customer's monthly price changed over time (upgrades, promotions). Leave
**Auto-calculate** on unless you are modelling a specific billing history.

**Internet Service ↔ Add-on Services** — in the dataset, all 1,526 customers without internet have
*"No internet service"* for all six add-ons, with **zero exceptions**. The add-ons below stay editable,
but if you set Internet Service to *"No"* the model input is coerced to match the dataset's encoding
(the app tells you when it does this). The same applies to Phone Service ↔ Multiple Lines.

**What the model actually consumes** — `tenure`, `MonthlyCharges`, `TotalCharges`, plus two engineered
features: `ContractRiskScore` (Month-to-month = 2, One year = 1, Two year = 0) and
`ChargesToTenureRatio` = `MonthlyCharges / (tenure + 1)`.
        """)

    st.markdown('<div class="grp">Customer profile</div>', unsafe_allow_html=True)
    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown("**Demographics**")
        gender = st.selectbox("Gender", ["Female", "Male"], key="in_gender")
        senior_citizen = st.selectbox("Senior Citizen", ["No", "Yes"], key="in_senior")
        partner = st.selectbox("Has Partner", ["No", "Yes"], key="in_partner")
        dependents = st.selectbox("Has Dependents", ["No", "Yes"], key="in_dependents")

    with col2:
        st.markdown("**Contract & billing**")
        tenure = st.slider("Tenure (months)", 0, 72, 12, key="in_tenure",
                           help="How long the customer has been with the company.")
        contract = st.selectbox("Contract Type", ["Month-to-month", "One year", "Two year"],
                                key="in_contract",
                                help="The customer's CURRENT contract — independent of tenure. "
                                     "A long-tenured customer can still be month-to-month.")
        paperless_billing = st.selectbox("Paperless Billing", ["No", "Yes"], key="in_paperless")
        payment_method = st.selectbox(
            "Payment Method",
            ["Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"],
            key="in_payment",
            help="Electronic check and Mailed check are manual; the other two are automatic.")

    with col3:
        st.markdown("**Charges**")
        monthly_charges = st.slider("Monthly Charges (USD)", 18.0, 120.0, 70.0, step=0.5,
                                    key="in_monthly")
        auto_total = st.checkbox(
            "Auto-calculate Total Charges", value=True, key="in_auto_total",
            help="Total Charges = tenure x Monthly Charges. Accurate for ~95% of real customers; "
                 "untick to enter a specific billing history.")
        expected_total = round(tenure * monthly_charges, 2)
        if auto_total:
            total_charges = float(expected_total)
            st.metric("Total Charges (USD)", f"${total_charges:,.2f}",
                      help="tenure x Monthly Charges")
        else:
            total_charges = st.number_input(
                "Total Charges (USD)", min_value=0.0, value=float(expected_total),
                step=10.0, key="in_total_manual")

        # Plausibility feedback vs the real data
        ref = charges_consistency_reference()
        if expected_total > 0:
            dev_pct = (total_charges - expected_total) / expected_total * 100
            if abs(dev_pct) <= 10:
                st.caption(f"✅ {dev_pct:+.1f}% vs tenure x monthly — typical "
                           f"({ref['within_10pct']:.0f}% of real customers are within ±10%).")
            elif abs(dev_pct) <= 25:
                st.caption(f"⚠️ {dev_pct:+.1f}% vs tenure x monthly — possible but uncommon "
                           f"(implies the monthly price changed a lot over time).")
            else:
                st.caption(f"🚩 {dev_pct:+.1f}% vs tenure x monthly — outside anything in the "
                           f"training data; the prediction will be an extrapolation.")
        elif total_charges > 0:
            st.caption("🚩 Tenure is 0 but Total Charges is not — the 11 real zero-tenure "
                       "customers all have Total Charges = 0 (Section 3.1).")

    # --- Contract vs tenure plausibility, straight from the data -------------
    share, churn_ref, counts = contract_tenure_reference()
    tband = pd.cut([tenure], [-1, 12, 24, 48, 60, 200],
                   labels=["0-12", "13-24", "25-48", "49-60", "61+"])[0]
    pct_share = float(share.loc[tband, contract])
    n_cell = int(counts.loc[tband, contract])
    obs_churn = float(churn_ref.loc[tband, contract])
    common = share.loc[tband].idxmax()
    tone = "green" if pct_share >= 30 else ("amber" if pct_share >= 8 else "blue")
    st.markdown(
        f'<div class="finding {tone}">📌 <b>Tenure {tenure} months ({tband}) + {contract}</b> — '
        f'{pct_share:.1f}% of real customers in this tenure band hold this contract '
        f'(<b>{n_cell:,} customers</b>), and their observed churn rate is <b>{obs_churn:.1f}%</b>. '
        f'Most common contract in this band: <b>{common}</b>. '
        f'All combinations are valid — contract type is the current agreement, not a lifetime lock-in.</div>',
        unsafe_allow_html=True)

    # --- Services -------------------------------------------------------------
    st.markdown('<div class="grp">Services</div>', unsafe_allow_html=True)
    s1, s2 = st.columns(2)
    with s1:
        phone_service = st.selectbox("Phone Service", ["No", "Yes"], index=1, key="in_phone")
        multiple_lines = st.selectbox("Multiple Lines", ["No", "Yes"], key="in_lines")
    with s2:
        internet_service = st.selectbox("Internet Service", ["DSL", "Fiber optic", "No"],
                                        key="in_internet")

    st.markdown("**Internet add-on services**")
    a1, a2, a3 = st.columns(3)
    addon_vals = {}
    for i, svc in enumerate(ADDON_SERVICES):
        label = {"OnlineSecurity": "Online Security", "OnlineBackup": "Online Backup",
                 "DeviceProtection": "Device Protection", "TechSupport": "Tech Support",
                 "StreamingTV": "Streaming TV", "StreamingMovies": "Streaming Movies"}[svc]
        with [a1, a2, a3][i % 3]:
            addon_vals[svc] = st.selectbox(label, ["No", "Yes"], key=f"in_{svc}")

    # Coercion notices — the add-ons stay editable, but the model input is made
    # consistent with the dataset's encoding, and the user is told when that happens.
    coerced = []
    if internet_service == "No":
        turned_on = [s for s, v in addon_vals.items() if v == "Yes"]
        if turned_on:
            coerced.append(
                f"Internet Service is <b>No</b>, so {len(turned_on)} add-on(s) "
                f"({', '.join(turned_on)}) are sent to the model as "
                f'<b>"No internet service"</b> — all 1,526 such customers in the dataset '
                "are encoded that way, with zero exceptions.")
    if phone_service == "No" and multiple_lines == "Yes":
        coerced.append('Phone Service is <b>No</b>, so Multiple Lines is sent as '
                       '<b>"No phone service"</b> (682 such customers, zero exceptions).')
    if coerced:
        st.markdown('<div class="finding amber">⚠️ ' + "<br>".join(coerced) + "</div>",
                    unsafe_allow_html=True)

    # --- Derived features preview ------------------------------------------------
    ctr = monthly_charges / (tenure + 1)
    crs = CONTRACT_RISK[contract]
    with st.expander("🔧 Engineered features the model derives from these inputs", expanded=False):
        e1, e2 = st.columns(2)
        e1.metric("ChargesToTenureRatio", f"{ctr:.2f}",
                  help="MonthlyCharges / (tenure + 1) — the strongest single predictor "
                       "(r = 0.412 with churn, Section 2.6.1).")
        e2.metric("ContractRiskScore", crs,
                  help="Month-to-month = 2, One year = 1, Two year = 0 (r = 0.397 with churn).")
        st.caption("These two engineered features outrank every raw column in the tree models' "
                   "importance rankings (Section 5.3).")

    # The button + result block runs as a fragment: clicking Predict only reruns this
    # function, not the whole script (Data Analysis / Models tab computations are
    # skipped), so the result appears snappily with no full-page flash — and the
    # smooth CSS/Plotly transitions below actually get a chance to play.
    @st.fragment
    def render_prediction(gender, senior_citizen, partner, dependents, tenure, contract,
                          paperless_billing, payment_method, monthly_charges, total_charges,
                          phone_service, multiple_lines, internet_service, addon_vals,
                          model_name, model, models, feature_columns, scaler):
        predict_clicked = st.button(f"🔮  Predict Churn Risk  ·  {model_name}",
                                    width="stretch", type="primary")

        if predict_clicked:
            eff_addons = dict(addon_vals)
            eff_lines = multiple_lines
            if internet_service == "No":
                eff_addons = {s: "No" for s in ADDON_SERVICES}
            if phone_service == "No":
                eff_lines = "No"

            raw_input = pd.DataFrame([{
                "customerID": "PROTOTYPE-INPUT", "gender": gender,
                "SeniorCitizen": 1 if senior_citizen == "Yes" else 0,
                "Partner": partner, "Dependents": dependents, "tenure": tenure,
                "PhoneService": phone_service, "MultipleLines": eff_lines,
                "InternetService": internet_service,
                "OnlineSecurity": eff_addons["OnlineSecurity"],
                "OnlineBackup": eff_addons["OnlineBackup"],
                "DeviceProtection": eff_addons["DeviceProtection"],
                "TechSupport": eff_addons["TechSupport"],
                "StreamingTV": eff_addons["StreamingTV"],
                "StreamingMovies": eff_addons["StreamingMovies"],
                "Contract": contract, "PaperlessBilling": paperless_billing,
                "PaymentMethod": payment_method, "MonthlyCharges": monthly_charges,
                "TotalCharges": total_charges, "Churn": "No",
            }])

            cleaned = engineer_and_clean(raw_input)
            X_input = build_feature_matrix_proto(cleaned).reindex(columns=feature_columns, fill_value=0)
            X_input_scaled = X_input.copy()
            X_input_scaled[NUM_COLS_TO_SCALE] = scaler.transform(X_input[NUM_COLS_TO_SCALE])

            proba = float(model.predict_proba(X_input_scaled)[0, 1])
            if proba < 0.40:
                risk_label, risk_color, badge_class = "LOW RISK", GREEN, "risk-badge"
            elif proba < 0.70:
                risk_label, risk_color, badge_class = "MEDIUM RISK", AMBER, "risk-badge"
            else:
                risk_label, risk_color, badge_class = "HIGH RISK", RED, "risk-badge pulse"

            st.divider()
            st.subheader("Prediction Result")
            r1, r2 = st.columns([1, 2])
            with r1:
                st.metric(f"Churn Probability · {model_name}", f"{proba*100:.1f}%",
                          delta=f"{(proba - 0.2654)*100:+.1f} pp vs base rate")
            with r2:
                st.markdown(f'<div class="{badge_class}" style="background:{risk_color}">{risk_label}</div>',
                            unsafe_allow_html=True)
                st.markdown(
                    f'<div class="gauge"><div class="gauge-fill" '
                    f'style="width:{proba*100:.0f}%;background:{risk_color}"></div></div>',
                    unsafe_allow_html=True)
                st.caption("Low < 40%  ·  Medium 40–70%  ·  High > 70%   "
                           "(dataset base churn rate: 26.5%)")
            if risk_label == "LOW RISK":
                st.balloons()

            # top contributing features
            st.markdown("##### Top factors influencing this prediction")
            if hasattr(model, "feature_importances_"):
                importances = pd.Series(model.feature_importances_, index=feature_columns)
                imp_col, imp_note = f"{model_name} Importance", (
                    f"Global feature importance for {model_name} (Section 5.3), "
                    "shown against this customer's value.")
            else:
                importances = pd.Series(np.abs(model.coef_[0]), index=feature_columns)
                imp_col, imp_note = f"{model_name} |Coefficient|", (
                    f"{model_name} has no feature_importances_; absolute standardised coefficient "
                    "shown instead (Section 5.4).")
            top_features = importances.sort_values(ascending=False).head(6)
            rows = []
            for feat in top_features.index:
                val = X_input.iloc[0][feat]
                rows.append({"Feature": feat, imp_col: round(top_features[feat], 3),
                             "This customer": round(val, 2) if isinstance(val, (int, float, np.integer, np.floating)) else val})
            st.dataframe(pd.DataFrame(rows), hide_index=True, width="stretch")
            st.caption(imp_note + " Global ranking, not a per-prediction SHAP explanation (future work).")

            # all four models on this customer
            st.markdown("##### All four models — churn probability for this customer")
            all_probs = {n: float(mm.predict_proba(X_input_scaled)[0, 1]) * 100 for n, mm in models.items()}
            pdf = pd.DataFrame({"Model": list(all_probs), "Churn probability (%)": list(all_probs.values())})
            mc1, mc2 = st.columns([2, 1])
            with mc1:
                st.dataframe(
                    pdf.style.format({"Churn probability (%)": "{:.1f}"})
                       .background_gradient(cmap="Reds", subset=["Churn probability (%)"]),
                    hide_index=True, width="stretch")
            with mc2:
                spread = max(all_probs.values()) - min(all_probs.values())
                st.metric("Model agreement spread", f"{spread:.1f} pp",
                          help="Range between the most and least alarmed model. A wide spread means "
                               "the models disagree about this customer.")
            with st.expander("Show raw model input (debug)"):
                st.dataframe(X_input.T, width="stretch")
        else:
            st.info("Adjust the profile above, then click **Predict Churn Risk**. "
                    "Use the sidebar presets to jump to the highest- or lowest-risk segment "
                    "identified in the report.")

    render_prediction(gender, senior_citizen, partner, dependents, tenure, contract,
                      paperless_billing, payment_method, monthly_charges, total_charges,
                      phone_service, multiple_lines, internet_service, addon_vals,
                      model_name, model, models, feature_columns, scaler)

# ======================================================================
# TAB 2 — DATA ANALYSIS  (report Sections 2-3, every analysis, computed live)
# ======================================================================
with tab_analysis:
    df_eda, X_full, y_full = load_eda_data()

    (da_overview, da_univariate, da_engineered, da_interact,
     da_stats, da_quality, da_vif) = st.tabs([
        "2.1-2.3 Overview", "2.5 Univariate", "2.6 Engineered Features",
        "2.7 Interactions", "2.8 Statistical Tests", "3.1-3.2 Data Quality", "3.3 VIF",
    ])

    # -- 2.1-2.3 Overview & summary statistics -------------------------
    with da_overview:
        sec("2.1-2.3", "Dataset Overview & Summary Statistics")
        o1, o2, o3, o4 = st.columns(4)
        o1.metric("Customers", f"{len(df_eda):,}")
        o2.metric("Original attributes", "21")
        o3.metric("Churn rate", f"{(df_eda['Churn']=='Yes').mean()*100:.1f}%")
        o4.metric("Avg tenure", f"{df_eda['tenure'].mean():.1f} mo")

        target_df = eda.target_distribution(df_eda)
        c1, c2 = st.columns([1, 2])
        with c1:
            st.markdown("**Target distribution (Table)**")
            st.dataframe(target_df, width="stretch")
        with c2:
            st.markdown("**Figure 1 — Target Distribution (Chart)**")
            st.plotly_chart(pc.plot_target_distribution_plotly(df_eda),
                            width="stretch", key="target_dist_chart")

        st.markdown("**Table 4 — Summary statistics for numerical features**")
        summary_cols = ["tenure", "MonthlyCharges", "TotalCharges", "SeniorCitizen"]
        st.dataframe(eda.summary_statistics(df_eda, summary_cols).style.format("{:.2f}"),
                     width="stretch")
        st.caption("Average tenure ~32 months with a std almost as large as the mean — a mix of "
                   "new and long-established customers, not a homogeneous base (Section 2.3).")

    # -- 2.5 Univariate & bivariate patterns ----------------------------
    with da_univariate:
        sec("2.5", "Univariate and Bivariate Churn Patterns")
        pick_col = st.selectbox(
            "Churn rate by category —  pick a feature",
            ["Contract", "InternetService", "PaymentMethod", "SeniorCitizen", "PaperlessBilling",
             "Partner", "Dependents", "gender", "TechSupport", "OnlineSecurity"],
            index=0,
        )
        u1, u2 = st.columns([1, 1])
        with u1:
            st.dataframe(eda.churn_rate_by_category(df_eda, pick_col), width="stretch")
        with u2:
            st.markdown(f"**Churn rate by {pick_col}**")
            st.plotly_chart(pc.plot_churn_rate_by_category_plotly(df_eda, pick_col),
                            width="stretch", key="churn_by_cat_chart")

        st.markdown("**All categorical features at once (Figure 2a)**")
        st.plotly_chart(pc.plot_churn_rate_small_multiples_plotly(df_eda),
                        width="stretch", key="small_multiples_chart")
        st.markdown(
            '<div class="finding">Month-to-month churns at <b>42.7%</b> vs <b>2.8%</b> for two-year '
            '(15x gap). Electronic-check (manual) payers churn at <b>45.3%</b> vs 15-17% for automatic '
            'methods (Section 2.5).</div>', unsafe_allow_html=True)

        st.markdown("**Numeric features by churn class — distributions (Figure 2b) & boxplots (Figure 2c)**")
        n1, n2 = st.columns(2)
        with n1:
            st.plotly_chart(pc.plot_numeric_distributions_by_churn_plotly(df_eda),
                            width="stretch", key="numeric_dist_chart")
        with n2:
            st.plotly_chart(pc.plot_numeric_boxplots_by_churn_plotly(df_eda),
                            width="stretch", key="numeric_box_chart")

    # -- 2.6 Engineered feature audit -----------------------------------
    with da_engineered:
        sec("2.6", "Engineered Feature Audit",
            "8 features were derived from the existing 21 columns; each is checked directly "
            "against the data rather than assumed useful.")

        e1, e2 = st.columns([1, 1])
        with e1:
            st.markdown("**Figure 4 — Correlation of numeric/engineered features with churn**")
            st.plotly_chart(pc.plot_correlation_with_target_plotly(df_eda, epl.CORR_COLS),
                            width="stretch", key="corr_target_chart")
        with e2:
            st.markdown("**Figure 4a — Correlation heatmap** (interactive — hover for exact r)")
            st.plotly_chart(pc.plot_correlation_heatmap_plotly(df_eda, epl.CORR_COLS),
                            width="stretch", key="corr_heatmap")
        st.markdown(
            '<div class="finding green"><b>ChargesToTenureRatio (r=0.412)</b> and '
            '<b>ContractRiskScore (r=0.397)</b> beat every raw numeric column — the direct, data-driven '
            'justification for keeping both in the model (Section 2.6.1).</div>', unsafe_allow_html=True)

        st.markdown("**Figure 3 — Churn rate by TenureGroup** (descriptive only, not modelled)")
        f1, f2 = st.columns([1, 1])
        with f1:
            st.dataframe(eda.churn_rate_by_category(df_eda, "TenureGroup"), width="stretch")
        with f2:
            st.plotly_chart(pc.plot_churn_rate_by_tenuregroup_plotly(df_eda),
                            width="stretch", key="tenuregroup_chart")

        st.markdown("**2.6.2 — TotalServicesSubscribed: a non-monotonic pattern**")
        st.dataframe(eda.churn_rate_by_category(df_eda, "TotalServicesSubscribed"), width="stretch")
        st.caption("Weak overall correlation (r = -0.067) and non-monotonic on its own — Section 2.7 "
                   "shows the real relationship only appears once tenure is held fixed.")

        with st.expander("Validation evidence for the 3 rejected engineered features"):
            audit = eda.validate_engineered_features(df_eda)
            st.markdown("**HasInternetService vs InternetService** — collapsing hides the Fiber-vs-DSL split:")
            st.json(audit["HasInternetService_vs_InternetService"])
            st.markdown("**HasPartnerOrDependents vs Partner alone** — adds nothing beyond Partner:")
            st.json(audit["HasPartnerOrDependents_vs_Partner"])
            st.markdown(f"**AvgChargePerMonth vs MonthlyCharges** correlation: "
                       f"`{audit['AvgChargePerMonth_vs_MonthlyCharges_corr']}` (near-perfect duplicate)")
            st.markdown(f"**TotalServicesSubscribed vs manual service-flag sum** correlation: "
                       f"`{audit['TotalServicesSubscribed_vs_manual_sum_corr']}` (exact duplicate, dropped from modelling)")

    # -- 2.7 Multivariate interactions -----------------------------------
    with da_interact:
        sec("2.7", "Multivariate Interaction Analysis",
            "Where the most actionable findings turned up — combinations that single-variable "
            "views (Section 2.5) cannot show.")
        i1, i2 = st.columns(2)
        with i1:
            st.markdown("**Figure 5 — Contract × payment automation**")
            st.plotly_chart(pc.plot_interaction_heatmap_plotly(
                df_eda, "Contract", "IsAutoPay",
                row_order=["Month-to-month", "One year", "Two year"]),
                width="stretch", key="contract_autopay_chart")
            st.markdown(
                '<div class="finding"><b>Month-to-month + manual pay = 46.5%</b>, the highest-risk '
                'segment in the dataset. Two-year churns at 2.8-2.9% regardless of payment method — '
                'contract commitment cancels out payment friction almost entirely.</div>',
                unsafe_allow_html=True)
        with i2:
            st.markdown("**Figure 5b — Tenure group × number of services**")
            st.plotly_chart(pc.plot_tenure_service_interaction_plotly(df_eda),
                            width="stretch", key="tenure_service_chart")
            st.markdown(
                '<div class="finding blue">Within <b>every</b> tenure band, churn <b>rises</b> with '
                'service count — the opposite of the raw pattern in 2.6.2. First-year customers with '
                '4-5 services peak at <b>56.9%</b> (early bill shock, not loyalty).</div>',
                unsafe_allow_html=True)

    # -- 2.8 Statistical association tests --------------------------------
    with da_stats:
        sec("2.8", "Statistical Association Tests",
            "Chi-square + Cramer's V for categoricals; point-biserial correlation for numerics — "
            "hypothesis testing rather than visual inspection alone.")
        chi_df = eda.chi_square_tests(df_eda, [c for c in epl.CHI_CAT_COLS if c in df_eda.columns])
        pb_df = eda.point_biserial_tests(df_eda, [c for c in epl.CORR_COLS if c in df_eda.columns])

        s1, s2 = st.columns([3, 2])
        with s1:
            st.markdown("**Table 6a — Chi-square test + Cramer's V (categorical features)**")
            st.dataframe(
                chi_df.style.format({"chi2": "{:.1f}", "p_value": "{:.2e}", "cramers_v": "{:.3f}"})
                    .background_gradient(cmap="Reds", subset=["cramers_v"]),
                hide_index=True, width="stretch", height=420)
        with s2:
            st.markdown("**Figure 5a — Cramer's V association strength**")
            st.plotly_chart(pc.plot_cramers_v_plotly(chi_df), width="stretch", key="cramers_v_chart")

        st.markdown(
            '<div class="finding">Every categorical feature rejects independence from churn at '
            'p&lt;0.05 <b>except gender (p=0.487) and PhoneService (p=0.339)</b> — statistically '
            'unrelated. Only Contract (V=0.410), InternetService (0.322) and PaymentMethod (0.303) '
            'reach a <b>moderate</b> association; the rest are weak or negligible.</div>',
            unsafe_allow_html=True)

        st.markdown("**Table 6b — Point-biserial correlation (numeric/engineered features)**")
        st.dataframe(
            pb_df.style.format({"point_biserial_r": "{:+.3f}", "p_value": "{:.2e}"})
                .background_gradient(cmap="RdBu_r", subset=["point_biserial_r"], vmin=-0.5, vmax=0.5),
            hide_index=True, width="stretch")

    # -- 3.1-3.2 Data quality & outliers ------------------------------------
    with da_quality:
        sec("3.1-3.2", "Data Quality: Missing Values, Invalid Values, Outliers, Duplicates")

        df_raw = dp.load_data()
        total_charges_numeric = pd.to_numeric(df_raw["TotalCharges"], errors="coerce")
        n_missing = int(total_charges_numeric.isna().sum())
        q1, q2, q3 = st.columns(3)
        q1.metric("Missing TotalCharges (after coerce)", n_missing)
        q2.metric("All missing have tenure = 0", "Yes" if (df_raw.loc[total_charges_numeric.isna(), "tenure"] == 0).all() else "No")
        q3.metric("Imputation method", "Fill 0 (logic-based)")
        st.caption("3.1 — Blank strings pass an initial isnull() check; pd.to_numeric(errors='coerce') "
                   "reveals the 11 true NaNs, all brand-new (tenure=0) customers imputed as 0, not the "
                   "population median/mean.")

        st.markdown("**3.2 — Invalid value check** (boolean filter for negative values)")
        num_cols_chk = ["tenure", "MonthlyCharges", "TotalCharges", "TotalServicesSubscribed",
                        "AvgChargePerMonth", "ChargesToTenureRatio"]
        st.dataframe(eda.check_invalid_values(df_eda, num_cols_chk), hide_index=True, width="stretch")

        st.markdown("**3.2 — Outlier detection (mean ± 3σ)**")
        outliers = eda.detect_outliers_zscore(df_eda, num_cols_chk)
        st.dataframe(pd.DataFrame(outliers).T, width="stretch")

        st.markdown("**ChargesToTenureRatio outlier profile** — noise or genuine signal?")
        st.dataframe(eda.profile_outlier_group(df_eda, "ChargesToTenureRatio", profile_cols=["tenure"]),
                     hide_index=True, width="stretch")
        st.markdown(
            '<div class="finding">248 records (3.52%) exceed the 3σ bound — almost all brand-new '
            'customers already paying a high rate, churning at <b>83.1%</b> vs 26.5% overall. '
            'A genuine high-risk signal, kept rather than removed (Section 3.2).</div>',
            unsafe_allow_html=True)

        st.markdown("**Duplicate rows / IDs**")
        st.json(eda.check_duplicate_rows(df_eda))

    # -- 3.3 Multicollinearity (VIF) -----------------------------------------
    with da_vif:
        sec("3.3", "Multicollinearity Check (VIF)",
            "Four rounds of redundancy removal, from a worst-case VIF of 2,346 down to ~20 "
            "(recomputed live on the final 23-predictor feature matrix).")
        vif_df = compute_vif_table(tuple(feature_columns))
        v1, v2 = st.columns([1, 1])
        with v1:
            st.markdown("**VIF table (all 23 predictors)**")
            st.dataframe(vif_df.style.format({"VIF": "{:.2f}"})
                        .background_gradient(cmap="Reds", subset=["VIF"]),
                       hide_index=True, width="stretch", height=520)
        with v2:
            st.markdown("**VIF chart — top 15 by value**")
            st.plotly_chart(pc.plot_vif_plotly(vif_df), width="stretch", key="vif_chart")
        st.markdown(
            f'<div class="finding">Final max VIF ≈ <b>{vif_df["VIF"].max():.1f}</b> '
            f'({vif_df.iloc[0]["feature"]}), down from a worst case of 2,346 partway through the '
            'four-round audit (Section 3.3). Residual 10-20 range reflects genuine, disclosed '
            'correlation among tenure/charges/InternetService.</div>', unsafe_allow_html=True)

# ======================================================================
# TAB 3 — MODELS  (report Sections 4-5, full evaluation suite, computed live)
# ======================================================================
with tab_models:
    X_train_sm, y_train_sm, X_test_scaled, y_test = build_eval_bundle(tuple(feature_columns))

    (mo_perf, mo_curves, mo_confuse, mo_importance,
     mo_tree, mo_overfit, mo_threshold, mo_cv) = st.tabs([
        "5.2 Performance", "5.6 ROC / PR", "5.2 Confusion", "5.3-5.4 Importance",
        "5.5 Decision Tree", "5.8 Overfitting", "5.7 Threshold", "4.3 Cross-Validation",
    ])

    # -- 5.1-5.2 Performance overview -------------------------------------
    with mo_perf:
        sec("5.1-5.2", "Evaluation Metrics & Model Performance Comparison")
        dummy = ev.dummy_baseline(X_train_sm, y_train_sm, X_test_scaled, y_test)
        d1, d2, d3, d4 = st.columns(4)
        d1.metric("Dummy Accuracy", f"{dummy['Accuracy']*100:.1f}%")
        d2.metric("Dummy Precision", f"{dummy['Precision']*100:.1f}%")
        d3.metric("Dummy Recall", f"{dummy['Recall']*100:.1f}%")
        d4.metric("Dummy F1", f"{dummy['F1']*100:.1f}%")
        st.caption("5.1 — A majority-class dummy classifier reaches competitive Accuracy but scores "
                   "0.0 on Precision/Recall/F1 — empirical proof Accuracy alone would mislead here.")

        results_df = ev.evaluate_all_models(models, X_test_scaled, y_test)
        st.markdown("**Table 7 — Accuracy / Precision / Recall / F1 / AUC (test set, n=1,409)**")
        st.dataframe(
            (results_df * 100).assign(AUC=results_df["AUC"]).style
                .format({"Accuracy": "{:.2f}", "Precision": "{:.2f}", "Recall": "{:.2f}",
                        "F1": "{:.2f}", "AUC": "{:.3f}"})
                .highlight_max(axis=0, props=f"background-color:{LIGHT};font-weight:700;"),
            width="stretch")
        st.markdown("**Figure 8 — Model Performance Comparison**")
        st.plotly_chart(pc.plot_model_comparison_plotly(results_df), width="stretch",
                        key="model_comparison_chart")

    # -- 5.6 ROC / PR curves -----------------------------------------------
    with mo_curves:
        sec("5.2 / 5.6", "ROC Curves & Precision-Recall Curves")
        c1, c2 = st.columns(2)
        with c1:
            st.markdown("**Figure 6 — ROC curves** (interactive — hover for exact threshold)")
            st.plotly_chart(pc.plot_roc_curves_plotly(models, X_test_scaled, y_test),
                            width="stretch", key="roc_chart")
        with c2:
            st.markdown("**Figure 11 — Precision-Recall curves**")
            st.plotly_chart(pc.plot_pr_curves_plotly(models, X_test_scaled, y_test),
                            width="stretch", key="pr_chart")
        st.markdown(
            '<div class="finding blue">ROC-AUC ranks Random Forest first, but Average Precision '
            '(more informative on an imbalanced target) ranks Logistic Regression marginally ahead '
            '(0.650 vs 0.647) — reporting both avoids overselling either metric (Section 5.6).</div>',
            unsafe_allow_html=True)

    # -- 5.2 Confusion matrices ---------------------------------------------
    with mo_confuse:
        sec("5.2", "Confusion Matrices", "Test set, n = 1,409.")
        st.markdown("**Figure 7 — Confusion Matrices (all four models)**")
        st.plotly_chart(pc.plot_confusion_matrices_plotly(models, X_test_scaled, y_test),
                        width="stretch", key="confusion_chart")

    # -- 5.3-5.4 Feature importance / LR coefficients ------------------------
    with mo_importance:
        sec("5.3-5.4", "Feature Importance & Logistic Regression Coefficients")
        i1, i2 = st.columns(2)
        with i1:
            st.markdown("**Figure 9 — Random Forest top-10 importance**")
            rf_imp = ev.get_feature_importance(models["Random Forest"], feature_columns)
            st.plotly_chart(pc.plot_feature_importance_plotly(rf_imp),
                            width="stretch", key="rf_importance_chart")
        with i2:
            st.markdown("**XGBoost top-10 importance**")
            xgb_imp = ev.get_feature_importance(models["XGBoost"], feature_columns)
            st.plotly_chart(pc.plot_feature_importance_plotly(xgb_imp),
                            width="stretch", key="xgb_importance_chart")
        st.markdown(
            f'<div class="finding green">ChargesToTenureRatio leads Random Forest '
            f'(<b>{rf_imp.iloc[0]:.3f}</b>); ContractRiskScore dominates XGBoost '
            f'(<b>{xgb_imp.iloc[0]:.3f}</b>). Both engineered features outrank every raw column '
            'they were built from (Section 5.3).</div>', unsafe_allow_html=True)

        st.markdown("**Table 8 — Logistic Regression coefficients & odds ratios**")
        lr_coefs = ev.get_lr_coefficients(models["Logistic Regression"], feature_columns)
        oc1, oc2 = st.columns(2)
        oc1.markdown("Top positive (higher churn odds)")
        oc1.dataframe(lr_coefs.head(8).style.format({"coefficient": "{:.3f}", "odds_ratio": "{:.3f}"}),
                     width="stretch")
        oc2.markdown("Top negative (lower churn odds)")
        oc2.dataframe(lr_coefs.tail(8).sort_values("coefficient").style.format(
            {"coefficient": "{:.3f}", "odds_ratio": "{:.3f}"}), width="stretch")

    # -- 5.5 Decision tree structure ------------------------------------------
    with mo_tree:
        sec("5.5", "Decision Tree Structure", "Figure 12 — top 3 of 5 trained levels, for readability.")
        show_fig(ev.plot_decision_tree_structure(models["Decision Tree"], feature_columns, max_depth_display=3))
        st.caption("The root-node split is on a contract/charges-related feature before any demographic "
                  "attribute — a rule-based echo of the Section 2.7 interaction finding.")

    # -- 5.8 Overfitting check --------------------------------------------------
    with mo_overfit:
        sec("5.8", "Overfitting Check", "Train F1 (SMOTE-balanced) vs Test F1 (natural imbalance).")
        overfit_df = ev.overfitting_check(models, X_train_sm, y_train_sm, X_test_scaled, y_test)
        oc1, oc2 = st.columns([1, 1])
        with oc1:
            st.markdown("**Overfitting table**")
            st.dataframe(overfit_df.style.format("{:.3f}").background_gradient(cmap="Reds", subset=["Gap"]),
                       width="stretch")
        with oc2:
            st.markdown("**Figure 10 — Train vs Test F1**")
            st.plotly_chart(pc.plot_overfit_check_plotly(overfit_df),
                            width="stretch", key="overfit_chart")
        st.caption("An initial unconstrained Random Forest overfit severely (train F1 0.999 vs test 0.584); "
                  "regularised GridSearchCV settings shrink this gap while improving test F1 (Section 4.2/5.8).")

    # -- 5.7 Threshold tuning ------------------------------------------------------
    @st.fragment
    def render_threshold_tab(models, X_test_scaled, y_test, default_model_name):
        sec("5.7", "Threshold Tuning", "Sweeping the classification threshold away from the 0.5 default.")
        thr_model_name = st.selectbox("Model to sweep", list(models.keys()),
                                      index=list(models.keys()).index(default_model_name), key="thr_model")
        opt = ev.optimal_threshold(models[thr_model_name], X_test_scaled, y_test)
        t1, t2, t3 = st.columns(3)
        t1.metric("F1-optimal threshold", f"{opt['threshold']:.2f}")
        t2.metric("F1 at optimum", f"{opt['f1']:.3f}")
        t3.metric("Recall at optimum", f"{opt['recall']:.3f}")

        st.markdown("**🎚️ Explore any threshold live**")
        explore_thr = st.slider("Classification threshold", 0.10, 0.90, float(opt["threshold"]),
                                step=0.02, key="explore_thr",
                                help="Drag to see Precision/Recall/F1 update live, and the marker "
                                     "line move on the chart below.")
        live = pc.metrics_at_threshold(models[thr_model_name], X_test_scaled, y_test, explore_thr)
        l1, l2, l3 = st.columns(3)
        l1.metric("Precision @ threshold", f"{live['precision']:.3f}")
        l2.metric("Recall @ threshold", f"{live['recall']:.3f}")
        l3.metric("F1 @ threshold", f"{live['f1']:.3f}")

        st.markdown("**Figure 13 — F1-score vs Classification Threshold**")
        st.plotly_chart(
            pc.plot_threshold_curve_plotly(models, X_test_scaled, y_test,
                                           model_names_to_plot=list(models.keys()),
                                           marker_threshold=explore_thr),
            width="stretch", key="threshold_chart")
        st.caption("5.7/5.9 — Churn prediction has an asymmetric cost (a missed churner costs far more "
                  "than a false alarm), so operating below the default 0.5 threshold can trade a little "
                  "Precision for meaningfully higher Recall without retraining anything.")

    with mo_threshold:
        render_threshold_tab(models, X_test_scaled, y_test, model_name)

    # -- 4.3 Cross-validation --------------------------------------------------
    with mo_cv:
        sec("4.3", "5-Fold Stratified Cross-Validation (All Models)",
            "Confirms Section 5.2's single-split results are stable, not a lucky/unlucky split. "
            "SMOTE is applied fresh inside each fold.")
        cv_df = compute_cv_results()
        st.dataframe(cv_df.style.format("{:.3f}"), width="stretch")
        st.caption("Cross-validated means line up with the hold-out results within 1-2 percentage "
                  "points, with standard deviations mostly under 3pp — performance is stable across "
                  "partitions of the data, not dependent on this one split.")

st.divider()
st.caption(
    "Four models trained on 23 predictors after a four-round multicollinearity audit "
    "(Section 3.3 of the report): Logistic Regression, Decision Tree, Random Forest, XGBoost. "
    "Random Forest is the recommended default (Section 5.9) — test-set Accuracy 75.9%, "
    "Precision 53.3%, Recall 73.3%, F1 61.7%, AUC 0.839. Data Analysis and Models tabs run every "
    "report analysis live against the src/ package — this is not a static screenshot."
)
